// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: document.proto

package com.example.protobuf;

public final class DocumentProto {
  private DocumentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DocumentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Document)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.ShoppingList shopping_list = 1;</code>
     * @return Whether the shoppingList field is set.
     */
    boolean hasShoppingList();
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.ShoppingList shopping_list = 1;</code>
     * @return The shoppingList.
     */
    com.example.protobuf.DocumentProto.ShoppingList getShoppingList();
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.ShoppingList shopping_list = 1;</code>
     */
    com.example.protobuf.DocumentProto.ShoppingListOrBuilder getShoppingListOrBuilder();

    public com.example.protobuf.DocumentProto.Document.DocumentTypeCase getDocumentTypeCase();
  }
  /**
   * Protobuf type {@code Document}
   */
  public static final class Document extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Document)
      DocumentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Document.newBuilder() to construct.
    private Document(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Document() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Document();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.DocumentProto.internal_static_Document_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.DocumentProto.internal_static_Document_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.DocumentProto.Document.class, com.example.protobuf.DocumentProto.Document.Builder.class);
    }

    private int documentTypeCase_ = 0;
    private java.lang.Object documentType_;
    public enum DocumentTypeCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      SHOPPING_LIST(1),
      DOCUMENTTYPE_NOT_SET(0);
      private final int value;
      private DocumentTypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DocumentTypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static DocumentTypeCase forNumber(int value) {
        switch (value) {
          case 1: return SHOPPING_LIST;
          case 0: return DOCUMENTTYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DocumentTypeCase
    getDocumentTypeCase() {
      return DocumentTypeCase.forNumber(
          documentTypeCase_);
    }

    public static final int SHOPPING_LIST_FIELD_NUMBER = 1;
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.ShoppingList shopping_list = 1;</code>
     * @return Whether the shoppingList field is set.
     */
    @java.lang.Override
    public boolean hasShoppingList() {
      return documentTypeCase_ == 1;
    }
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.ShoppingList shopping_list = 1;</code>
     * @return The shoppingList.
     */
    @java.lang.Override
    public com.example.protobuf.DocumentProto.ShoppingList getShoppingList() {
      if (documentTypeCase_ == 1) {
         return (com.example.protobuf.DocumentProto.ShoppingList) documentType_;
      }
      return com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance();
    }
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.ShoppingList shopping_list = 1;</code>
     */
    @java.lang.Override
    public com.example.protobuf.DocumentProto.ShoppingListOrBuilder getShoppingListOrBuilder() {
      if (documentTypeCase_ == 1) {
         return (com.example.protobuf.DocumentProto.ShoppingList) documentType_;
      }
      return com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (documentTypeCase_ == 1) {
        output.writeMessage(1, (com.example.protobuf.DocumentProto.ShoppingList) documentType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (documentTypeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.example.protobuf.DocumentProto.ShoppingList) documentType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.DocumentProto.Document)) {
        return super.equals(obj);
      }
      com.example.protobuf.DocumentProto.Document other = (com.example.protobuf.DocumentProto.Document) obj;

      if (!getDocumentTypeCase().equals(other.getDocumentTypeCase())) return false;
      switch (documentTypeCase_) {
        case 1:
          if (!getShoppingList()
              .equals(other.getShoppingList())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (documentTypeCase_) {
        case 1:
          hash = (37 * hash) + SHOPPING_LIST_FIELD_NUMBER;
          hash = (53 * hash) + getShoppingList().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.DocumentProto.Document parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.Document parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.protobuf.DocumentProto.Document parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.DocumentProto.Document parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.DocumentProto.Document prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Document}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Document)
        com.example.protobuf.DocumentProto.DocumentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.DocumentProto.internal_static_Document_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.DocumentProto.internal_static_Document_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.DocumentProto.Document.class, com.example.protobuf.DocumentProto.Document.Builder.class);
      }

      // Construct using com.example.protobuf.DocumentProto.Document.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (shoppingListBuilder_ != null) {
          shoppingListBuilder_.clear();
        }
        documentTypeCase_ = 0;
        documentType_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.DocumentProto.internal_static_Document_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.DocumentProto.Document getDefaultInstanceForType() {
        return com.example.protobuf.DocumentProto.Document.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.DocumentProto.Document build() {
        com.example.protobuf.DocumentProto.Document result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.DocumentProto.Document buildPartial() {
        com.example.protobuf.DocumentProto.Document result = new com.example.protobuf.DocumentProto.Document(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.protobuf.DocumentProto.Document result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(com.example.protobuf.DocumentProto.Document result) {
        result.documentTypeCase_ = documentTypeCase_;
        result.documentType_ = this.documentType_;
        if (documentTypeCase_ == 1 &&
            shoppingListBuilder_ != null) {
          result.documentType_ = shoppingListBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.DocumentProto.Document) {
          return mergeFrom((com.example.protobuf.DocumentProto.Document)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.DocumentProto.Document other) {
        if (other == com.example.protobuf.DocumentProto.Document.getDefaultInstance()) return this;
        switch (other.getDocumentTypeCase()) {
          case SHOPPING_LIST: {
            mergeShoppingList(other.getShoppingList());
            break;
          }
          case DOCUMENTTYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getShoppingListFieldBuilder().getBuilder(),
                    extensionRegistry);
                documentTypeCase_ = 1;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int documentTypeCase_ = 0;
      private java.lang.Object documentType_;
      public DocumentTypeCase
          getDocumentTypeCase() {
        return DocumentTypeCase.forNumber(
            documentTypeCase_);
      }

      public Builder clearDocumentType() {
        documentTypeCase_ = 0;
        documentType_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.protobuf.DocumentProto.ShoppingList, com.example.protobuf.DocumentProto.ShoppingList.Builder, com.example.protobuf.DocumentProto.ShoppingListOrBuilder> shoppingListBuilder_;
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       * @return Whether the shoppingList field is set.
       */
      @java.lang.Override
      public boolean hasShoppingList() {
        return documentTypeCase_ == 1;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       * @return The shoppingList.
       */
      @java.lang.Override
      public com.example.protobuf.DocumentProto.ShoppingList getShoppingList() {
        if (shoppingListBuilder_ == null) {
          if (documentTypeCase_ == 1) {
            return (com.example.protobuf.DocumentProto.ShoppingList) documentType_;
          }
          return com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance();
        } else {
          if (documentTypeCase_ == 1) {
            return shoppingListBuilder_.getMessage();
          }
          return com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       */
      public Builder setShoppingList(com.example.protobuf.DocumentProto.ShoppingList value) {
        if (shoppingListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          documentType_ = value;
          onChanged();
        } else {
          shoppingListBuilder_.setMessage(value);
        }
        documentTypeCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       */
      public Builder setShoppingList(
          com.example.protobuf.DocumentProto.ShoppingList.Builder builderForValue) {
        if (shoppingListBuilder_ == null) {
          documentType_ = builderForValue.build();
          onChanged();
        } else {
          shoppingListBuilder_.setMessage(builderForValue.build());
        }
        documentTypeCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       */
      public Builder mergeShoppingList(com.example.protobuf.DocumentProto.ShoppingList value) {
        if (shoppingListBuilder_ == null) {
          if (documentTypeCase_ == 1 &&
              documentType_ != com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance()) {
            documentType_ = com.example.protobuf.DocumentProto.ShoppingList.newBuilder((com.example.protobuf.DocumentProto.ShoppingList) documentType_)
                .mergeFrom(value).buildPartial();
          } else {
            documentType_ = value;
          }
          onChanged();
        } else {
          if (documentTypeCase_ == 1) {
            shoppingListBuilder_.mergeFrom(value);
          } else {
            shoppingListBuilder_.setMessage(value);
          }
        }
        documentTypeCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       */
      public Builder clearShoppingList() {
        if (shoppingListBuilder_ == null) {
          if (documentTypeCase_ == 1) {
            documentTypeCase_ = 0;
            documentType_ = null;
            onChanged();
          }
        } else {
          if (documentTypeCase_ == 1) {
            documentTypeCase_ = 0;
            documentType_ = null;
          }
          shoppingListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       */
      public com.example.protobuf.DocumentProto.ShoppingList.Builder getShoppingListBuilder() {
        return getShoppingListFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       */
      @java.lang.Override
      public com.example.protobuf.DocumentProto.ShoppingListOrBuilder getShoppingListOrBuilder() {
        if ((documentTypeCase_ == 1) && (shoppingListBuilder_ != null)) {
          return shoppingListBuilder_.getMessageOrBuilder();
        } else {
          if (documentTypeCase_ == 1) {
            return (com.example.protobuf.DocumentProto.ShoppingList) documentType_;
          }
          return com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.ShoppingList shopping_list = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.protobuf.DocumentProto.ShoppingList, com.example.protobuf.DocumentProto.ShoppingList.Builder, com.example.protobuf.DocumentProto.ShoppingListOrBuilder> 
          getShoppingListFieldBuilder() {
        if (shoppingListBuilder_ == null) {
          if (!(documentTypeCase_ == 1)) {
            documentType_ = com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance();
          }
          shoppingListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.protobuf.DocumentProto.ShoppingList, com.example.protobuf.DocumentProto.ShoppingList.Builder, com.example.protobuf.DocumentProto.ShoppingListOrBuilder>(
                  (com.example.protobuf.DocumentProto.ShoppingList) documentType_,
                  getParentForChildren(),
                  isClean());
          documentType_ = null;
        }
        documentTypeCase_ = 1;
        onChanged();
        return shoppingListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Document)
    }

    // @@protoc_insertion_point(class_scope:Document)
    private static final com.example.protobuf.DocumentProto.Document DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.DocumentProto.Document();
    }

    public static com.example.protobuf.DocumentProto.Document getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Document>
        PARSER = new com.google.protobuf.AbstractParser<Document>() {
      @java.lang.Override
      public Document parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Document> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Document> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.DocumentProto.Document getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShoppingListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ShoppingList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    boolean containsItems(
        java.lang.String key);
    /**
     * Use {@link #getItemsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getItems();
    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getItemsMap();
    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    int getItemsOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    int getItemsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code ShoppingList}
   */
  public static final class ShoppingList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ShoppingList)
      ShoppingListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShoppingList.newBuilder() to construct.
    private ShoppingList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShoppingList() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShoppingList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.DocumentProto.internal_static_ShoppingList_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetItems();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.DocumentProto.internal_static_ShoppingList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.DocumentProto.ShoppingList.class, com.example.protobuf.DocumentProto.ShoppingList.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private static final class ItemsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.example.protobuf.DocumentProto.internal_static_ShoppingList_ItemsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> items_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetItems() {
      if (items_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ItemsDefaultEntryHolder.defaultEntry);
      }
      return items_;
    }
    public int getItemsCount() {
      return internalGetItems().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    @java.lang.Override
    public boolean containsItems(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetItems().getMap().containsKey(key);
    }
    /**
     * Use {@link #getItemsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getItems() {
      return getItemsMap();
    }
    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Integer> getItemsMap() {
      return internalGetItems().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    @java.lang.Override
    public int getItemsOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetItems().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; items = 1;</code>
     */
    @java.lang.Override
    public int getItemsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetItems().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetItems(),
          ItemsDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetItems().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        items__ = ItemsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, items__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.DocumentProto.ShoppingList)) {
        return super.equals(obj);
      }
      com.example.protobuf.DocumentProto.ShoppingList other = (com.example.protobuf.DocumentProto.ShoppingList) obj;

      if (!internalGetItems().equals(
          other.internalGetItems())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetItems().getMap().isEmpty()) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetItems().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.DocumentProto.ShoppingList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.DocumentProto.ShoppingList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ShoppingList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ShoppingList)
        com.example.protobuf.DocumentProto.ShoppingListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.DocumentProto.internal_static_ShoppingList_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.DocumentProto.internal_static_ShoppingList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.DocumentProto.ShoppingList.class, com.example.protobuf.DocumentProto.ShoppingList.Builder.class);
      }

      // Construct using com.example.protobuf.DocumentProto.ShoppingList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableItems().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.DocumentProto.internal_static_ShoppingList_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.DocumentProto.ShoppingList getDefaultInstanceForType() {
        return com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.DocumentProto.ShoppingList build() {
        com.example.protobuf.DocumentProto.ShoppingList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.DocumentProto.ShoppingList buildPartial() {
        com.example.protobuf.DocumentProto.ShoppingList result = new com.example.protobuf.DocumentProto.ShoppingList(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.protobuf.DocumentProto.ShoppingList result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.items_ = internalGetItems();
          result.items_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.DocumentProto.ShoppingList) {
          return mergeFrom((com.example.protobuf.DocumentProto.ShoppingList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.DocumentProto.ShoppingList other) {
        if (other == com.example.protobuf.DocumentProto.ShoppingList.getDefaultInstance()) return this;
        internalGetMutableItems().mergeFrom(
            other.internalGetItems());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
                items__ = input.readMessage(
                    ItemsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableItems().getMutableMap().put(
                    items__.getKey(), items__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> items_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
          internalGetItems() {
        if (items_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ItemsDefaultEntryHolder.defaultEntry);
        }
        return items_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
          internalGetMutableItems() {
        if (items_ == null) {
          items_ = com.google.protobuf.MapField.newMapField(
              ItemsDefaultEntryHolder.defaultEntry);
        }
        if (!items_.isMutable()) {
          items_ = items_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return items_;
      }
      public int getItemsCount() {
        return internalGetItems().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; items = 1;</code>
       */
      @java.lang.Override
      public boolean containsItems(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetItems().getMap().containsKey(key);
      }
      /**
       * Use {@link #getItemsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getItems() {
        return getItemsMap();
      }
      /**
       * <code>map&lt;string, int32&gt; items = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.Integer> getItemsMap() {
        return internalGetItems().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; items = 1;</code>
       */
      @java.lang.Override
      public int getItemsOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetItems().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; items = 1;</code>
       */
      @java.lang.Override
      public int getItemsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetItems().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearItems() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableItems().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; items = 1;</code>
       */
      public Builder removeItems(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableItems().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
          getMutableItems() {
        bitField0_ |= 0x00000001;
        return internalGetMutableItems().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; items = 1;</code>
       */
      public Builder putItems(
          java.lang.String key,
          int value) {
        if (key == null) { throw new NullPointerException("map key"); }
        
        internalGetMutableItems().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; items = 1;</code>
       */
      public Builder putAllItems(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableItems().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ShoppingList)
    }

    // @@protoc_insertion_point(class_scope:ShoppingList)
    private static final com.example.protobuf.DocumentProto.ShoppingList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.DocumentProto.ShoppingList();
    }

    public static com.example.protobuf.DocumentProto.ShoppingList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShoppingList>
        PARSER = new com.google.protobuf.AbstractParser<ShoppingList>() {
      @java.lang.Override
      public ShoppingList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ShoppingList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShoppingList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.DocumentProto.ShoppingList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Document_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Document_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShoppingList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ShoppingList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShoppingList_ItemsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ShoppingList_ItemsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016document.proto\"C\n\010Document\022&\n\rshopping" +
      "_list\030\001 \001(\0132\r.ShoppingListH\000B\017\n\rdocument" +
      "_type\"e\n\014ShoppingList\022\'\n\005items\030\001 \003(\0132\030.S" +
      "hoppingList.ItemsEntry\032,\n\nItemsEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001B%\n\024com.exam" +
      "ple.protobufB\rDocumentProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Document_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Document_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Document_descriptor,
        new java.lang.String[] { "ShoppingList", "DocumentType", });
    internal_static_ShoppingList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ShoppingList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ShoppingList_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_ShoppingList_ItemsEntry_descriptor =
      internal_static_ShoppingList_descriptor.getNestedTypes().get(0);
    internal_static_ShoppingList_ItemsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ShoppingList_ItemsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
