// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: awmap.proto

package feup.sdle.message;

public final class AWMapProto {
  private AWMapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AWMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:feup.sdle.message.AWMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
     * @return Whether the dotContext field is set.
     */
    boolean hasDotContext();
    /**
     * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
     * @return The dotContext.
     */
    feup.sdle.message.DotContextProto.DotContext getDotContext();
    /**
     * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
     */
    feup.sdle.message.DotContextProto.DotContextOrBuilder getDotContextOrBuilder();

    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     * @return Whether the localIdentifier field is set.
     */
    boolean hasLocalIdentifier();
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     * @return The localIdentifier.
     */
    feup.sdle.message.NodeIdentifierMessage.NodeIdentifier getLocalIdentifier();
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     */
    feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder getLocalIdentifierOrBuilder();

    /**
     * <code>.feup.sdle.message.AWSet keys = 3;</code>
     * @return Whether the keys field is set.
     */
    boolean hasKeys();
    /**
     * <code>.feup.sdle.message.AWSet keys = 3;</code>
     * @return The keys.
     */
    feup.sdle.message.AWSetProto.AWSet getKeys();
    /**
     * <code>.feup.sdle.message.AWSet keys = 3;</code>
     */
    feup.sdle.message.AWSetProto.AWSetOrBuilder getKeysOrBuilder();

    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    int getValuesCount();
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    boolean containsValues(
        java.lang.String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
    getValues();
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
    getValuesMap();
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    /* nullable */
feup.sdle.message.DottedValueProto.DottedValue getValuesOrDefault(
        java.lang.String key,
        /* nullable */
feup.sdle.message.DottedValueProto.DottedValue defaultValue);
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    feup.sdle.message.DottedValueProto.DottedValue getValuesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code feup.sdle.message.AWMap}
   */
  public static final class AWMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:feup.sdle.message.AWMap)
      AWMapOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AWMap.newBuilder() to construct.
    private AWMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AWMap() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AWMap();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return feup.sdle.message.AWMapProto.internal_static_feup_sdle_message_AWMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return feup.sdle.message.AWMapProto.internal_static_feup_sdle_message_AWMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              feup.sdle.message.AWMapProto.AWMap.class, feup.sdle.message.AWMapProto.AWMap.Builder.class);
    }

    public static final int DOTCONTEXT_FIELD_NUMBER = 1;
    private feup.sdle.message.DotContextProto.DotContext dotContext_;
    /**
     * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
     * @return Whether the dotContext field is set.
     */
    @java.lang.Override
    public boolean hasDotContext() {
      return dotContext_ != null;
    }
    /**
     * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
     * @return The dotContext.
     */
    @java.lang.Override
    public feup.sdle.message.DotContextProto.DotContext getDotContext() {
      return dotContext_ == null ? feup.sdle.message.DotContextProto.DotContext.getDefaultInstance() : dotContext_;
    }
    /**
     * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
     */
    @java.lang.Override
    public feup.sdle.message.DotContextProto.DotContextOrBuilder getDotContextOrBuilder() {
      return dotContext_ == null ? feup.sdle.message.DotContextProto.DotContext.getDefaultInstance() : dotContext_;
    }

    public static final int LOCALIDENTIFIER_FIELD_NUMBER = 2;
    private feup.sdle.message.NodeIdentifierMessage.NodeIdentifier localIdentifier_;
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     * @return Whether the localIdentifier field is set.
     */
    @java.lang.Override
    public boolean hasLocalIdentifier() {
      return localIdentifier_ != null;
    }
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     * @return The localIdentifier.
     */
    @java.lang.Override
    public feup.sdle.message.NodeIdentifierMessage.NodeIdentifier getLocalIdentifier() {
      return localIdentifier_ == null ? feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance() : localIdentifier_;
    }
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     */
    @java.lang.Override
    public feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder getLocalIdentifierOrBuilder() {
      return localIdentifier_ == null ? feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance() : localIdentifier_;
    }

    public static final int KEYS_FIELD_NUMBER = 3;
    private feup.sdle.message.AWSetProto.AWSet keys_;
    /**
     * <code>.feup.sdle.message.AWSet keys = 3;</code>
     * @return Whether the keys field is set.
     */
    @java.lang.Override
    public boolean hasKeys() {
      return keys_ != null;
    }
    /**
     * <code>.feup.sdle.message.AWSet keys = 3;</code>
     * @return The keys.
     */
    @java.lang.Override
    public feup.sdle.message.AWSetProto.AWSet getKeys() {
      return keys_ == null ? feup.sdle.message.AWSetProto.AWSet.getDefaultInstance() : keys_;
    }
    /**
     * <code>.feup.sdle.message.AWSet keys = 3;</code>
     */
    @java.lang.Override
    public feup.sdle.message.AWSetProto.AWSetOrBuilder getKeysOrBuilder() {
      return keys_ == null ? feup.sdle.message.AWSetProto.AWSet.getDefaultInstance() : keys_;
    }

    public static final int VALUES_FIELD_NUMBER = 4;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>newDefaultInstance(
                  feup.sdle.message.AWMapProto.internal_static_feup_sdle_message_AWMap_ValuesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  feup.sdle.message.DottedValueProto.DottedValue.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> values_;
    private com.google.protobuf.MapField<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }
    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    @java.lang.Override
    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
feup.sdle.message.DottedValueProto.DottedValue getValuesOrDefault(
        java.lang.String key,
        /* nullable */
feup.sdle.message.DottedValueProto.DottedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
     */
    @java.lang.Override
    public feup.sdle.message.DottedValueProto.DottedValue getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dotContext_ != null) {
        output.writeMessage(1, getDotContext());
      }
      if (localIdentifier_ != null) {
        output.writeMessage(2, getLocalIdentifier());
      }
      if (keys_ != null) {
        output.writeMessage(3, getKeys());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          4);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dotContext_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDotContext());
      }
      if (localIdentifier_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLocalIdentifier());
      }
      if (keys_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getKeys());
      }
      for (java.util.Map.Entry<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, values__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof feup.sdle.message.AWMapProto.AWMap)) {
        return super.equals(obj);
      }
      feup.sdle.message.AWMapProto.AWMap other = (feup.sdle.message.AWMapProto.AWMap) obj;

      if (hasDotContext() != other.hasDotContext()) return false;
      if (hasDotContext()) {
        if (!getDotContext()
            .equals(other.getDotContext())) return false;
      }
      if (hasLocalIdentifier() != other.hasLocalIdentifier()) return false;
      if (hasLocalIdentifier()) {
        if (!getLocalIdentifier()
            .equals(other.getLocalIdentifier())) return false;
      }
      if (hasKeys() != other.hasKeys()) return false;
      if (hasKeys()) {
        if (!getKeys()
            .equals(other.getKeys())) return false;
      }
      if (!internalGetValues().equals(
          other.internalGetValues())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDotContext()) {
        hash = (37 * hash) + DOTCONTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getDotContext().hashCode();
      }
      if (hasLocalIdentifier()) {
        hash = (37 * hash) + LOCALIDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getLocalIdentifier().hashCode();
      }
      if (hasKeys()) {
        hash = (37 * hash) + KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getKeys().hashCode();
      }
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static feup.sdle.message.AWMapProto.AWMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.AWMapProto.AWMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(feup.sdle.message.AWMapProto.AWMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code feup.sdle.message.AWMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:feup.sdle.message.AWMap)
        feup.sdle.message.AWMapProto.AWMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return feup.sdle.message.AWMapProto.internal_static_feup_sdle_message_AWMap_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return feup.sdle.message.AWMapProto.internal_static_feup_sdle_message_AWMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                feup.sdle.message.AWMapProto.AWMap.class, feup.sdle.message.AWMapProto.AWMap.Builder.class);
      }

      // Construct using feup.sdle.message.AWMapProto.AWMap.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        dotContext_ = null;
        if (dotContextBuilder_ != null) {
          dotContextBuilder_.dispose();
          dotContextBuilder_ = null;
        }
        localIdentifier_ = null;
        if (localIdentifierBuilder_ != null) {
          localIdentifierBuilder_.dispose();
          localIdentifierBuilder_ = null;
        }
        keys_ = null;
        if (keysBuilder_ != null) {
          keysBuilder_.dispose();
          keysBuilder_ = null;
        }
        internalGetMutableValues().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return feup.sdle.message.AWMapProto.internal_static_feup_sdle_message_AWMap_descriptor;
      }

      @java.lang.Override
      public feup.sdle.message.AWMapProto.AWMap getDefaultInstanceForType() {
        return feup.sdle.message.AWMapProto.AWMap.getDefaultInstance();
      }

      @java.lang.Override
      public feup.sdle.message.AWMapProto.AWMap build() {
        feup.sdle.message.AWMapProto.AWMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public feup.sdle.message.AWMapProto.AWMap buildPartial() {
        feup.sdle.message.AWMapProto.AWMap result = new feup.sdle.message.AWMapProto.AWMap(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(feup.sdle.message.AWMapProto.AWMap result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.dotContext_ = dotContextBuilder_ == null
              ? dotContext_
              : dotContextBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.localIdentifier_ = localIdentifierBuilder_ == null
              ? localIdentifier_
              : localIdentifierBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.keys_ = keysBuilder_ == null
              ? keys_
              : keysBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.values_ = internalGetValues();
          result.values_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof feup.sdle.message.AWMapProto.AWMap) {
          return mergeFrom((feup.sdle.message.AWMapProto.AWMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(feup.sdle.message.AWMapProto.AWMap other) {
        if (other == feup.sdle.message.AWMapProto.AWMap.getDefaultInstance()) return this;
        if (other.hasDotContext()) {
          mergeDotContext(other.getDotContext());
        }
        if (other.hasLocalIdentifier()) {
          mergeLocalIdentifier(other.getLocalIdentifier());
        }
        if (other.hasKeys()) {
          mergeKeys(other.getKeys());
        }
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        bitField0_ |= 0x00000008;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getDotContextFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getLocalIdentifierFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getKeysFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
                values__ = input.readMessage(
                    ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableValues().getMutableMap().put(
                    values__.getKey(), values__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private feup.sdle.message.DotContextProto.DotContext dotContext_;
      private com.google.protobuf.SingleFieldBuilderV3<
          feup.sdle.message.DotContextProto.DotContext, feup.sdle.message.DotContextProto.DotContext.Builder, feup.sdle.message.DotContextProto.DotContextOrBuilder> dotContextBuilder_;
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       * @return Whether the dotContext field is set.
       */
      public boolean hasDotContext() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       * @return The dotContext.
       */
      public feup.sdle.message.DotContextProto.DotContext getDotContext() {
        if (dotContextBuilder_ == null) {
          return dotContext_ == null ? feup.sdle.message.DotContextProto.DotContext.getDefaultInstance() : dotContext_;
        } else {
          return dotContextBuilder_.getMessage();
        }
      }
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       */
      public Builder setDotContext(feup.sdle.message.DotContextProto.DotContext value) {
        if (dotContextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dotContext_ = value;
        } else {
          dotContextBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       */
      public Builder setDotContext(
          feup.sdle.message.DotContextProto.DotContext.Builder builderForValue) {
        if (dotContextBuilder_ == null) {
          dotContext_ = builderForValue.build();
        } else {
          dotContextBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       */
      public Builder mergeDotContext(feup.sdle.message.DotContextProto.DotContext value) {
        if (dotContextBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            dotContext_ != null &&
            dotContext_ != feup.sdle.message.DotContextProto.DotContext.getDefaultInstance()) {
            getDotContextBuilder().mergeFrom(value);
          } else {
            dotContext_ = value;
          }
        } else {
          dotContextBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       */
      public Builder clearDotContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dotContext_ = null;
        if (dotContextBuilder_ != null) {
          dotContextBuilder_.dispose();
          dotContextBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       */
      public feup.sdle.message.DotContextProto.DotContext.Builder getDotContextBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDotContextFieldBuilder().getBuilder();
      }
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       */
      public feup.sdle.message.DotContextProto.DotContextOrBuilder getDotContextOrBuilder() {
        if (dotContextBuilder_ != null) {
          return dotContextBuilder_.getMessageOrBuilder();
        } else {
          return dotContext_ == null ?
              feup.sdle.message.DotContextProto.DotContext.getDefaultInstance() : dotContext_;
        }
      }
      /**
       * <code>.feup.sdle.message.DotContext dotContext = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          feup.sdle.message.DotContextProto.DotContext, feup.sdle.message.DotContextProto.DotContext.Builder, feup.sdle.message.DotContextProto.DotContextOrBuilder> 
          getDotContextFieldBuilder() {
        if (dotContextBuilder_ == null) {
          dotContextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              feup.sdle.message.DotContextProto.DotContext, feup.sdle.message.DotContextProto.DotContext.Builder, feup.sdle.message.DotContextProto.DotContextOrBuilder>(
                  getDotContext(),
                  getParentForChildren(),
                  isClean());
          dotContext_ = null;
        }
        return dotContextBuilder_;
      }

      private feup.sdle.message.NodeIdentifierMessage.NodeIdentifier localIdentifier_;
      private com.google.protobuf.SingleFieldBuilderV3<
          feup.sdle.message.NodeIdentifierMessage.NodeIdentifier, feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder, feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder> localIdentifierBuilder_;
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       * @return Whether the localIdentifier field is set.
       */
      public boolean hasLocalIdentifier() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       * @return The localIdentifier.
       */
      public feup.sdle.message.NodeIdentifierMessage.NodeIdentifier getLocalIdentifier() {
        if (localIdentifierBuilder_ == null) {
          return localIdentifier_ == null ? feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance() : localIdentifier_;
        } else {
          return localIdentifierBuilder_.getMessage();
        }
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public Builder setLocalIdentifier(feup.sdle.message.NodeIdentifierMessage.NodeIdentifier value) {
        if (localIdentifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          localIdentifier_ = value;
        } else {
          localIdentifierBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public Builder setLocalIdentifier(
          feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder builderForValue) {
        if (localIdentifierBuilder_ == null) {
          localIdentifier_ = builderForValue.build();
        } else {
          localIdentifierBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public Builder mergeLocalIdentifier(feup.sdle.message.NodeIdentifierMessage.NodeIdentifier value) {
        if (localIdentifierBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            localIdentifier_ != null &&
            localIdentifier_ != feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance()) {
            getLocalIdentifierBuilder().mergeFrom(value);
          } else {
            localIdentifier_ = value;
          }
        } else {
          localIdentifierBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public Builder clearLocalIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localIdentifier_ = null;
        if (localIdentifierBuilder_ != null) {
          localIdentifierBuilder_.dispose();
          localIdentifierBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder getLocalIdentifierBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLocalIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder getLocalIdentifierOrBuilder() {
        if (localIdentifierBuilder_ != null) {
          return localIdentifierBuilder_.getMessageOrBuilder();
        } else {
          return localIdentifier_ == null ?
              feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance() : localIdentifier_;
        }
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          feup.sdle.message.NodeIdentifierMessage.NodeIdentifier, feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder, feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder> 
          getLocalIdentifierFieldBuilder() {
        if (localIdentifierBuilder_ == null) {
          localIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              feup.sdle.message.NodeIdentifierMessage.NodeIdentifier, feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder, feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder>(
                  getLocalIdentifier(),
                  getParentForChildren(),
                  isClean());
          localIdentifier_ = null;
        }
        return localIdentifierBuilder_;
      }

      private feup.sdle.message.AWSetProto.AWSet keys_;
      private com.google.protobuf.SingleFieldBuilderV3<
          feup.sdle.message.AWSetProto.AWSet, feup.sdle.message.AWSetProto.AWSet.Builder, feup.sdle.message.AWSetProto.AWSetOrBuilder> keysBuilder_;
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       * @return Whether the keys field is set.
       */
      public boolean hasKeys() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       * @return The keys.
       */
      public feup.sdle.message.AWSetProto.AWSet getKeys() {
        if (keysBuilder_ == null) {
          return keys_ == null ? feup.sdle.message.AWSetProto.AWSet.getDefaultInstance() : keys_;
        } else {
          return keysBuilder_.getMessage();
        }
      }
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       */
      public Builder setKeys(feup.sdle.message.AWSetProto.AWSet value) {
        if (keysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          keys_ = value;
        } else {
          keysBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       */
      public Builder setKeys(
          feup.sdle.message.AWSetProto.AWSet.Builder builderForValue) {
        if (keysBuilder_ == null) {
          keys_ = builderForValue.build();
        } else {
          keysBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       */
      public Builder mergeKeys(feup.sdle.message.AWSetProto.AWSet value) {
        if (keysBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            keys_ != null &&
            keys_ != feup.sdle.message.AWSetProto.AWSet.getDefaultInstance()) {
            getKeysBuilder().mergeFrom(value);
          } else {
            keys_ = value;
          }
        } else {
          keysBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       */
      public Builder clearKeys() {
        bitField0_ = (bitField0_ & ~0x00000004);
        keys_ = null;
        if (keysBuilder_ != null) {
          keysBuilder_.dispose();
          keysBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       */
      public feup.sdle.message.AWSetProto.AWSet.Builder getKeysBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getKeysFieldBuilder().getBuilder();
      }
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       */
      public feup.sdle.message.AWSetProto.AWSetOrBuilder getKeysOrBuilder() {
        if (keysBuilder_ != null) {
          return keysBuilder_.getMessageOrBuilder();
        } else {
          return keys_ == null ?
              feup.sdle.message.AWSetProto.AWSet.getDefaultInstance() : keys_;
        }
      }
      /**
       * <code>.feup.sdle.message.AWSet keys = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          feup.sdle.message.AWSetProto.AWSet, feup.sdle.message.AWSetProto.AWSet.Builder, feup.sdle.message.AWSetProto.AWSetOrBuilder> 
          getKeysFieldBuilder() {
        if (keysBuilder_ == null) {
          keysBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              feup.sdle.message.AWSetProto.AWSet, feup.sdle.message.AWSetProto.AWSet.Builder, feup.sdle.message.AWSetProto.AWSetOrBuilder>(
                  getKeys(),
                  getParentForChildren(),
                  isClean());
          keys_ = null;
        }
        return keysBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> values_;
      private com.google.protobuf.MapField<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
          internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
          internalGetMutableValues() {
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return values_;
      }
      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
       */
      @java.lang.Override
      public boolean containsValues(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> getValues() {
        return getValuesMap();
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
       */
      @java.lang.Override
      public /* nullable */
feup.sdle.message.DottedValueProto.DottedValue getValuesOrDefault(
          java.lang.String key,
          /* nullable */
feup.sdle.message.DottedValueProto.DottedValue defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
       */
      @java.lang.Override
      public feup.sdle.message.DottedValueProto.DottedValue getValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearValues() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
       */
      public Builder removeValues(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
          getMutableValues() {
        bitField0_ |= 0x00000008;
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
       */
      public Builder putValues(
          java.lang.String key,
          feup.sdle.message.DottedValueProto.DottedValue value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; values = 4;</code>
       */
      public Builder putAllValues(
          java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:feup.sdle.message.AWMap)
    }

    // @@protoc_insertion_point(class_scope:feup.sdle.message.AWMap)
    private static final feup.sdle.message.AWMapProto.AWMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new feup.sdle.message.AWMapProto.AWMap();
    }

    public static feup.sdle.message.AWMapProto.AWMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AWMap>
        PARSER = new com.google.protobuf.AbstractParser<AWMap>() {
      @java.lang.Override
      public AWMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AWMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AWMap> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public feup.sdle.message.AWMapProto.AWMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feup_sdle_message_AWMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feup_sdle_message_AWMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feup_sdle_message_AWMap_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feup_sdle_message_AWMap_ValuesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013awmap.proto\022\021feup.sdle.message\032\020dotcon" +
      "text.proto\032\024nodeidentifier.proto\032\021dotted" +
      "value.proto\032\013awset.proto\"\243\002\n\005AWMap\0221\n\ndo" +
      "tContext\030\001 \001(\0132\035.feup.sdle.message.DotCo" +
      "ntext\022:\n\017localIdentifier\030\002 \001(\0132!.feup.sd" +
      "le.message.NodeIdentifier\022&\n\004keys\030\003 \001(\0132" +
      "\030.feup.sdle.message.AWSet\0224\n\006values\030\004 \003(" +
      "\0132$.feup.sdle.message.AWMap.ValuesEntry\032" +
      "M\n\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022-\n\005value\030\002 \001" +
      "(\0132\036.feup.sdle.message.DottedValue:\0028\001B\037" +
      "\n\021feup.sdle.messageB\nAWMapProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          feup.sdle.message.DotContextProto.getDescriptor(),
          feup.sdle.message.NodeIdentifierMessage.getDescriptor(),
          feup.sdle.message.DottedValueProto.getDescriptor(),
          feup.sdle.message.AWSetProto.getDescriptor(),
        });
    internal_static_feup_sdle_message_AWMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_feup_sdle_message_AWMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feup_sdle_message_AWMap_descriptor,
        new java.lang.String[] { "DotContext", "LocalIdentifier", "Keys", "Values", });
    internal_static_feup_sdle_message_AWMap_ValuesEntry_descriptor =
      internal_static_feup_sdle_message_AWMap_descriptor.getNestedTypes().get(0);
    internal_static_feup_sdle_message_AWMap_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feup_sdle_message_AWMap_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    feup.sdle.message.DotContextProto.getDescriptor();
    feup.sdle.message.NodeIdentifierMessage.getDescriptor();
    feup.sdle.message.DottedValueProto.getDescriptor();
    feup.sdle.message.AWSetProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
