// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccounter.proto

package feup.sdle.message;

public final class CCounterProto {
  private CCounterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CCounterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:feup.sdle.message.CCounter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    java.util.List<feup.sdle.message.DottedValueProto.DottedValue> 
        getSetList();
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    feup.sdle.message.DottedValueProto.DottedValue getSet(int index);
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    int getSetCount();
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    java.util.List<? extends feup.sdle.message.DottedValueProto.DottedValueOrBuilder> 
        getSetOrBuilderList();
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    feup.sdle.message.DottedValueProto.DottedValueOrBuilder getSetOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code feup.sdle.message.CCounter}
   */
  public static final class CCounter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:feup.sdle.message.CCounter)
      CCounterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CCounter.newBuilder() to construct.
    private CCounter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CCounter() {
      set_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CCounter();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return feup.sdle.message.CCounterProto.internal_static_feup_sdle_message_CCounter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return feup.sdle.message.CCounterProto.internal_static_feup_sdle_message_CCounter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              feup.sdle.message.CCounterProto.CCounter.class, feup.sdle.message.CCounterProto.CCounter.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int SET_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<feup.sdle.message.DottedValueProto.DottedValue> set_;
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    @java.lang.Override
    public java.util.List<feup.sdle.message.DottedValueProto.DottedValue> getSetList() {
      return set_;
    }
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends feup.sdle.message.DottedValueProto.DottedValueOrBuilder> 
        getSetOrBuilderList() {
      return set_;
    }
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    @java.lang.Override
    public int getSetCount() {
      return set_.size();
    }
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    @java.lang.Override
    public feup.sdle.message.DottedValueProto.DottedValue getSet(int index) {
      return set_.get(index);
    }
    /**
     * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
     */
    @java.lang.Override
    public feup.sdle.message.DottedValueProto.DottedValueOrBuilder getSetOrBuilder(
        int index) {
      return set_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < set_.size(); i++) {
        output.writeMessage(2, set_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      for (int i = 0; i < set_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, set_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof feup.sdle.message.CCounterProto.CCounter)) {
        return super.equals(obj);
      }
      feup.sdle.message.CCounterProto.CCounter other = (feup.sdle.message.CCounterProto.CCounter) obj;

      if (getId()
          != other.getId()) return false;
      if (!getSetList()
          .equals(other.getSetList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (getSetCount() > 0) {
        hash = (37 * hash) + SET_FIELD_NUMBER;
        hash = (53 * hash) + getSetList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static feup.sdle.message.CCounterProto.CCounter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.CCounterProto.CCounter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(feup.sdle.message.CCounterProto.CCounter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code feup.sdle.message.CCounter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:feup.sdle.message.CCounter)
        feup.sdle.message.CCounterProto.CCounterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return feup.sdle.message.CCounterProto.internal_static_feup_sdle_message_CCounter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return feup.sdle.message.CCounterProto.internal_static_feup_sdle_message_CCounter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                feup.sdle.message.CCounterProto.CCounter.class, feup.sdle.message.CCounterProto.CCounter.Builder.class);
      }

      // Construct using feup.sdle.message.CCounterProto.CCounter.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        if (setBuilder_ == null) {
          set_ = java.util.Collections.emptyList();
        } else {
          set_ = null;
          setBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return feup.sdle.message.CCounterProto.internal_static_feup_sdle_message_CCounter_descriptor;
      }

      @java.lang.Override
      public feup.sdle.message.CCounterProto.CCounter getDefaultInstanceForType() {
        return feup.sdle.message.CCounterProto.CCounter.getDefaultInstance();
      }

      @java.lang.Override
      public feup.sdle.message.CCounterProto.CCounter build() {
        feup.sdle.message.CCounterProto.CCounter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public feup.sdle.message.CCounterProto.CCounter buildPartial() {
        feup.sdle.message.CCounterProto.CCounter result = new feup.sdle.message.CCounterProto.CCounter(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(feup.sdle.message.CCounterProto.CCounter result) {
        if (setBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            set_ = java.util.Collections.unmodifiableList(set_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.set_ = set_;
        } else {
          result.set_ = setBuilder_.build();
        }
      }

      private void buildPartial0(feup.sdle.message.CCounterProto.CCounter result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof feup.sdle.message.CCounterProto.CCounter) {
          return mergeFrom((feup.sdle.message.CCounterProto.CCounter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(feup.sdle.message.CCounterProto.CCounter other) {
        if (other == feup.sdle.message.CCounterProto.CCounter.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (setBuilder_ == null) {
          if (!other.set_.isEmpty()) {
            if (set_.isEmpty()) {
              set_ = other.set_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSetIsMutable();
              set_.addAll(other.set_);
            }
            onChanged();
          }
        } else {
          if (!other.set_.isEmpty()) {
            if (setBuilder_.isEmpty()) {
              setBuilder_.dispose();
              setBuilder_ = null;
              set_ = other.set_;
              bitField0_ = (bitField0_ & ~0x00000002);
              setBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSetFieldBuilder() : null;
            } else {
              setBuilder_.addAllMessages(other.set_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                feup.sdle.message.DottedValueProto.DottedValue m =
                    input.readMessage(
                        feup.sdle.message.DottedValueProto.DottedValue.parser(),
                        extensionRegistry);
                if (setBuilder_ == null) {
                  ensureSetIsMutable();
                  set_.add(m);
                } else {
                  setBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<feup.sdle.message.DottedValueProto.DottedValue> set_ =
        java.util.Collections.emptyList();
      private void ensureSetIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          set_ = new java.util.ArrayList<feup.sdle.message.DottedValueProto.DottedValue>(set_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          feup.sdle.message.DottedValueProto.DottedValue, feup.sdle.message.DottedValueProto.DottedValue.Builder, feup.sdle.message.DottedValueProto.DottedValueOrBuilder> setBuilder_;

      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public java.util.List<feup.sdle.message.DottedValueProto.DottedValue> getSetList() {
        if (setBuilder_ == null) {
          return java.util.Collections.unmodifiableList(set_);
        } else {
          return setBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public int getSetCount() {
        if (setBuilder_ == null) {
          return set_.size();
        } else {
          return setBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public feup.sdle.message.DottedValueProto.DottedValue getSet(int index) {
        if (setBuilder_ == null) {
          return set_.get(index);
        } else {
          return setBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder setSet(
          int index, feup.sdle.message.DottedValueProto.DottedValue value) {
        if (setBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSetIsMutable();
          set_.set(index, value);
          onChanged();
        } else {
          setBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder setSet(
          int index, feup.sdle.message.DottedValueProto.DottedValue.Builder builderForValue) {
        if (setBuilder_ == null) {
          ensureSetIsMutable();
          set_.set(index, builderForValue.build());
          onChanged();
        } else {
          setBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder addSet(feup.sdle.message.DottedValueProto.DottedValue value) {
        if (setBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSetIsMutable();
          set_.add(value);
          onChanged();
        } else {
          setBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder addSet(
          int index, feup.sdle.message.DottedValueProto.DottedValue value) {
        if (setBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSetIsMutable();
          set_.add(index, value);
          onChanged();
        } else {
          setBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder addSet(
          feup.sdle.message.DottedValueProto.DottedValue.Builder builderForValue) {
        if (setBuilder_ == null) {
          ensureSetIsMutable();
          set_.add(builderForValue.build());
          onChanged();
        } else {
          setBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder addSet(
          int index, feup.sdle.message.DottedValueProto.DottedValue.Builder builderForValue) {
        if (setBuilder_ == null) {
          ensureSetIsMutable();
          set_.add(index, builderForValue.build());
          onChanged();
        } else {
          setBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder addAllSet(
          java.lang.Iterable<? extends feup.sdle.message.DottedValueProto.DottedValue> values) {
        if (setBuilder_ == null) {
          ensureSetIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, set_);
          onChanged();
        } else {
          setBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder clearSet() {
        if (setBuilder_ == null) {
          set_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          setBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public Builder removeSet(int index) {
        if (setBuilder_ == null) {
          ensureSetIsMutable();
          set_.remove(index);
          onChanged();
        } else {
          setBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public feup.sdle.message.DottedValueProto.DottedValue.Builder getSetBuilder(
          int index) {
        return getSetFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public feup.sdle.message.DottedValueProto.DottedValueOrBuilder getSetOrBuilder(
          int index) {
        if (setBuilder_ == null) {
          return set_.get(index);  } else {
          return setBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public java.util.List<? extends feup.sdle.message.DottedValueProto.DottedValueOrBuilder> 
           getSetOrBuilderList() {
        if (setBuilder_ != null) {
          return setBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(set_);
        }
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public feup.sdle.message.DottedValueProto.DottedValue.Builder addSetBuilder() {
        return getSetFieldBuilder().addBuilder(
            feup.sdle.message.DottedValueProto.DottedValue.getDefaultInstance());
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public feup.sdle.message.DottedValueProto.DottedValue.Builder addSetBuilder(
          int index) {
        return getSetFieldBuilder().addBuilder(
            index, feup.sdle.message.DottedValueProto.DottedValue.getDefaultInstance());
      }
      /**
       * <code>repeated .feup.sdle.message.DottedValue set = 2;</code>
       */
      public java.util.List<feup.sdle.message.DottedValueProto.DottedValue.Builder> 
           getSetBuilderList() {
        return getSetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          feup.sdle.message.DottedValueProto.DottedValue, feup.sdle.message.DottedValueProto.DottedValue.Builder, feup.sdle.message.DottedValueProto.DottedValueOrBuilder> 
          getSetFieldBuilder() {
        if (setBuilder_ == null) {
          setBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              feup.sdle.message.DottedValueProto.DottedValue, feup.sdle.message.DottedValueProto.DottedValue.Builder, feup.sdle.message.DottedValueProto.DottedValueOrBuilder>(
                  set_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          set_ = null;
        }
        return setBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:feup.sdle.message.CCounter)
    }

    // @@protoc_insertion_point(class_scope:feup.sdle.message.CCounter)
    private static final feup.sdle.message.CCounterProto.CCounter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new feup.sdle.message.CCounterProto.CCounter();
    }

    public static feup.sdle.message.CCounterProto.CCounter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CCounter>
        PARSER = new com.google.protobuf.AbstractParser<CCounter>() {
      @java.lang.Override
      public CCounter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CCounter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CCounter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public feup.sdle.message.CCounterProto.CCounter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feup_sdle_message_CCounter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feup_sdle_message_CCounter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ccounter.proto\022\021feup.sdle.message\032\021dot" +
      "tedvalue.proto\"C\n\010CCounter\022\n\n\002id\030\001 \001(\005\022+" +
      "\n\003set\030\002 \003(\0132\036.feup.sdle.message.DottedVa" +
      "lueB\"\n\021feup.sdle.messageB\rCCounterProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          feup.sdle.message.DottedValueProto.getDescriptor(),
        });
    internal_static_feup_sdle_message_CCounter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_feup_sdle_message_CCounter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feup_sdle_message_CCounter_descriptor,
        new java.lang.String[] { "Id", "Set", });
    feup.sdle.message.DottedValueProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
