// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: document.proto
// Protobuf Java Version: 4.28.3

package feup.sdle.message;

public final class DocumentProto {
  private DocumentProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      DocumentProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DocumentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:feup.sdle.message.Document)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
     * @return Whether the shoppingList field is set.
     */
    boolean hasShoppingList();
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
     * @return The shoppingList.
     */
    feup.sdle.message.DocumentProto.ShoppingList getShoppingList();
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
     */
    feup.sdle.message.DocumentProto.ShoppingListOrBuilder getShoppingListOrBuilder();

    /**
     * <code>optional bool replicate = 2;</code>
     * @return Whether the replicate field is set.
     */
    boolean hasReplicate();
    /**
     * <code>optional bool replicate = 2;</code>
     * @return The replicate.
     */
    boolean getReplicate();

    feup.sdle.message.DocumentProto.Document.DocumentTypeCase getDocumentTypeCase();
  }
  /**
   * Protobuf type {@code feup.sdle.message.Document}
   */
  public static final class Document extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:feup.sdle.message.Document)
      DocumentOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Document.class.getName());
    }
    // Use Document.newBuilder() to construct.
    private Document(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Document() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_Document_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_Document_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              feup.sdle.message.DocumentProto.Document.class, feup.sdle.message.DocumentProto.Document.Builder.class);
    }

    private int bitField0_;
    private int documentTypeCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object documentType_;
    public enum DocumentTypeCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      SHOPPING_LIST(1),
      DOCUMENTTYPE_NOT_SET(0);
      private final int value;
      private DocumentTypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DocumentTypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static DocumentTypeCase forNumber(int value) {
        switch (value) {
          case 1: return SHOPPING_LIST;
          case 0: return DOCUMENTTYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DocumentTypeCase
    getDocumentTypeCase() {
      return DocumentTypeCase.forNumber(
          documentTypeCase_);
    }

    public static final int SHOPPING_LIST_FIELD_NUMBER = 1;
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
     * @return Whether the shoppingList field is set.
     */
    @java.lang.Override
    public boolean hasShoppingList() {
      return documentTypeCase_ == 1;
    }
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
     * @return The shoppingList.
     */
    @java.lang.Override
    public feup.sdle.message.DocumentProto.ShoppingList getShoppingList() {
      if (documentTypeCase_ == 1) {
         return (feup.sdle.message.DocumentProto.ShoppingList) documentType_;
      }
      return feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance();
    }
    /**
     * <pre>
     * Add other document types here in the future
     * </pre>
     *
     * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
     */
    @java.lang.Override
    public feup.sdle.message.DocumentProto.ShoppingListOrBuilder getShoppingListOrBuilder() {
      if (documentTypeCase_ == 1) {
         return (feup.sdle.message.DocumentProto.ShoppingList) documentType_;
      }
      return feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance();
    }

    public static final int REPLICATE_FIELD_NUMBER = 2;
    private boolean replicate_ = false;
    /**
     * <code>optional bool replicate = 2;</code>
     * @return Whether the replicate field is set.
     */
    @java.lang.Override
    public boolean hasReplicate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool replicate = 2;</code>
     * @return The replicate.
     */
    @java.lang.Override
    public boolean getReplicate() {
      return replicate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (documentTypeCase_ == 1) {
        output.writeMessage(1, (feup.sdle.message.DocumentProto.ShoppingList) documentType_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(2, replicate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (documentTypeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (feup.sdle.message.DocumentProto.ShoppingList) documentType_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, replicate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof feup.sdle.message.DocumentProto.Document)) {
        return super.equals(obj);
      }
      feup.sdle.message.DocumentProto.Document other = (feup.sdle.message.DocumentProto.Document) obj;

      if (hasReplicate() != other.hasReplicate()) return false;
      if (hasReplicate()) {
        if (getReplicate()
            != other.getReplicate()) return false;
      }
      if (!getDocumentTypeCase().equals(other.getDocumentTypeCase())) return false;
      switch (documentTypeCase_) {
        case 1:
          if (!getShoppingList()
              .equals(other.getShoppingList())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReplicate()) {
        hash = (37 * hash) + REPLICATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getReplicate());
      }
      switch (documentTypeCase_) {
        case 1:
          hash = (37 * hash) + SHOPPING_LIST_FIELD_NUMBER;
          hash = (53 * hash) + getShoppingList().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static feup.sdle.message.DocumentProto.Document parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static feup.sdle.message.DocumentProto.Document parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static feup.sdle.message.DocumentProto.Document parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentProto.Document parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(feup.sdle.message.DocumentProto.Document prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code feup.sdle.message.Document}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:feup.sdle.message.Document)
        feup.sdle.message.DocumentProto.DocumentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_Document_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_Document_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                feup.sdle.message.DocumentProto.Document.class, feup.sdle.message.DocumentProto.Document.Builder.class);
      }

      // Construct using feup.sdle.message.DocumentProto.Document.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (shoppingListBuilder_ != null) {
          shoppingListBuilder_.clear();
        }
        replicate_ = false;
        documentTypeCase_ = 0;
        documentType_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_Document_descriptor;
      }

      @java.lang.Override
      public feup.sdle.message.DocumentProto.Document getDefaultInstanceForType() {
        return feup.sdle.message.DocumentProto.Document.getDefaultInstance();
      }

      @java.lang.Override
      public feup.sdle.message.DocumentProto.Document build() {
        feup.sdle.message.DocumentProto.Document result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public feup.sdle.message.DocumentProto.Document buildPartial() {
        feup.sdle.message.DocumentProto.Document result = new feup.sdle.message.DocumentProto.Document(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(feup.sdle.message.DocumentProto.Document result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.replicate_ = replicate_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      private void buildPartialOneofs(feup.sdle.message.DocumentProto.Document result) {
        result.documentTypeCase_ = documentTypeCase_;
        result.documentType_ = this.documentType_;
        if (documentTypeCase_ == 1 &&
            shoppingListBuilder_ != null) {
          result.documentType_ = shoppingListBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof feup.sdle.message.DocumentProto.Document) {
          return mergeFrom((feup.sdle.message.DocumentProto.Document)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(feup.sdle.message.DocumentProto.Document other) {
        if (other == feup.sdle.message.DocumentProto.Document.getDefaultInstance()) return this;
        if (other.hasReplicate()) {
          setReplicate(other.getReplicate());
        }
        switch (other.getDocumentTypeCase()) {
          case SHOPPING_LIST: {
            mergeShoppingList(other.getShoppingList());
            break;
          }
          case DOCUMENTTYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getShoppingListFieldBuilder().getBuilder(),
                    extensionRegistry);
                documentTypeCase_ = 1;
                break;
              } // case 10
              case 16: {
                replicate_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int documentTypeCase_ = 0;
      private java.lang.Object documentType_;
      public DocumentTypeCase
          getDocumentTypeCase() {
        return DocumentTypeCase.forNumber(
            documentTypeCase_);
      }

      public Builder clearDocumentType() {
        documentTypeCase_ = 0;
        documentType_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          feup.sdle.message.DocumentProto.ShoppingList, feup.sdle.message.DocumentProto.ShoppingList.Builder, feup.sdle.message.DocumentProto.ShoppingListOrBuilder> shoppingListBuilder_;
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       * @return Whether the shoppingList field is set.
       */
      @java.lang.Override
      public boolean hasShoppingList() {
        return documentTypeCase_ == 1;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       * @return The shoppingList.
       */
      @java.lang.Override
      public feup.sdle.message.DocumentProto.ShoppingList getShoppingList() {
        if (shoppingListBuilder_ == null) {
          if (documentTypeCase_ == 1) {
            return (feup.sdle.message.DocumentProto.ShoppingList) documentType_;
          }
          return feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance();
        } else {
          if (documentTypeCase_ == 1) {
            return shoppingListBuilder_.getMessage();
          }
          return feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       */
      public Builder setShoppingList(feup.sdle.message.DocumentProto.ShoppingList value) {
        if (shoppingListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          documentType_ = value;
          onChanged();
        } else {
          shoppingListBuilder_.setMessage(value);
        }
        documentTypeCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       */
      public Builder setShoppingList(
          feup.sdle.message.DocumentProto.ShoppingList.Builder builderForValue) {
        if (shoppingListBuilder_ == null) {
          documentType_ = builderForValue.build();
          onChanged();
        } else {
          shoppingListBuilder_.setMessage(builderForValue.build());
        }
        documentTypeCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       */
      public Builder mergeShoppingList(feup.sdle.message.DocumentProto.ShoppingList value) {
        if (shoppingListBuilder_ == null) {
          if (documentTypeCase_ == 1 &&
              documentType_ != feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance()) {
            documentType_ = feup.sdle.message.DocumentProto.ShoppingList.newBuilder((feup.sdle.message.DocumentProto.ShoppingList) documentType_)
                .mergeFrom(value).buildPartial();
          } else {
            documentType_ = value;
          }
          onChanged();
        } else {
          if (documentTypeCase_ == 1) {
            shoppingListBuilder_.mergeFrom(value);
          } else {
            shoppingListBuilder_.setMessage(value);
          }
        }
        documentTypeCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       */
      public Builder clearShoppingList() {
        if (shoppingListBuilder_ == null) {
          if (documentTypeCase_ == 1) {
            documentTypeCase_ = 0;
            documentType_ = null;
            onChanged();
          }
        } else {
          if (documentTypeCase_ == 1) {
            documentTypeCase_ = 0;
            documentType_ = null;
          }
          shoppingListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       */
      public feup.sdle.message.DocumentProto.ShoppingList.Builder getShoppingListBuilder() {
        return getShoppingListFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       */
      @java.lang.Override
      public feup.sdle.message.DocumentProto.ShoppingListOrBuilder getShoppingListOrBuilder() {
        if ((documentTypeCase_ == 1) && (shoppingListBuilder_ != null)) {
          return shoppingListBuilder_.getMessageOrBuilder();
        } else {
          if (documentTypeCase_ == 1) {
            return (feup.sdle.message.DocumentProto.ShoppingList) documentType_;
          }
          return feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Add other document types here in the future
       * </pre>
       *
       * <code>.feup.sdle.message.ShoppingList shopping_list = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          feup.sdle.message.DocumentProto.ShoppingList, feup.sdle.message.DocumentProto.ShoppingList.Builder, feup.sdle.message.DocumentProto.ShoppingListOrBuilder> 
          getShoppingListFieldBuilder() {
        if (shoppingListBuilder_ == null) {
          if (!(documentTypeCase_ == 1)) {
            documentType_ = feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance();
          }
          shoppingListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              feup.sdle.message.DocumentProto.ShoppingList, feup.sdle.message.DocumentProto.ShoppingList.Builder, feup.sdle.message.DocumentProto.ShoppingListOrBuilder>(
                  (feup.sdle.message.DocumentProto.ShoppingList) documentType_,
                  getParentForChildren(),
                  isClean());
          documentType_ = null;
        }
        documentTypeCase_ = 1;
        onChanged();
        return shoppingListBuilder_;
      }

      private boolean replicate_ ;
      /**
       * <code>optional bool replicate = 2;</code>
       * @return Whether the replicate field is set.
       */
      @java.lang.Override
      public boolean hasReplicate() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bool replicate = 2;</code>
       * @return The replicate.
       */
      @java.lang.Override
      public boolean getReplicate() {
        return replicate_;
      }
      /**
       * <code>optional bool replicate = 2;</code>
       * @param value The replicate to set.
       * @return This builder for chaining.
       */
      public Builder setReplicate(boolean value) {

        replicate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool replicate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplicate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        replicate_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:feup.sdle.message.Document)
    }

    // @@protoc_insertion_point(class_scope:feup.sdle.message.Document)
    private static final feup.sdle.message.DocumentProto.Document DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new feup.sdle.message.DocumentProto.Document();
    }

    public static feup.sdle.message.DocumentProto.Document getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Document>
        PARSER = new com.google.protobuf.AbstractParser<Document>() {
      @java.lang.Override
      public Document parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Document> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Document> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public feup.sdle.message.DocumentProto.Document getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShoppingListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:feup.sdle.message.ShoppingList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.feup.sdle.message.AWMap items = 1;</code>
     * @return Whether the items field is set.
     */
    boolean hasItems();
    /**
     * <code>.feup.sdle.message.AWMap items = 1;</code>
     * @return The items.
     */
    feup.sdle.message.AWMapProto.AWMap getItems();
    /**
     * <code>.feup.sdle.message.AWMap items = 1;</code>
     */
    feup.sdle.message.AWMapProto.AWMapOrBuilder getItemsOrBuilder();

    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     * @return Whether the localIdentifier field is set.
     */
    boolean hasLocalIdentifier();
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     * @return The localIdentifier.
     */
    feup.sdle.message.NodeIdentifierMessage.NodeIdentifier getLocalIdentifier();
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     */
    feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder getLocalIdentifierOrBuilder();

    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    int getRemovedCountersCount();
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    boolean containsRemovedCounters(
        java.lang.String key);
    /**
     * Use {@link #getRemovedCountersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
    getRemovedCounters();
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
    getRemovedCountersMap();
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    /* nullable */
feup.sdle.message.DottedValueProto.DottedValue getRemovedCountersOrDefault(
        java.lang.String key,
        /* nullable */
feup.sdle.message.DottedValueProto.DottedValue defaultValue);
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    feup.sdle.message.DottedValueProto.DottedValue getRemovedCountersOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code feup.sdle.message.ShoppingList}
   */
  public static final class ShoppingList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:feup.sdle.message.ShoppingList)
      ShoppingListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        ShoppingList.class.getName());
    }
    // Use ShoppingList.newBuilder() to construct.
    private ShoppingList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ShoppingList() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_ShoppingList_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetRemovedCounters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_ShoppingList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              feup.sdle.message.DocumentProto.ShoppingList.class, feup.sdle.message.DocumentProto.ShoppingList.Builder.class);
    }

    private int bitField0_;
    public static final int ITEMS_FIELD_NUMBER = 1;
    private feup.sdle.message.AWMapProto.AWMap items_;
    /**
     * <code>.feup.sdle.message.AWMap items = 1;</code>
     * @return Whether the items field is set.
     */
    @java.lang.Override
    public boolean hasItems() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.feup.sdle.message.AWMap items = 1;</code>
     * @return The items.
     */
    @java.lang.Override
    public feup.sdle.message.AWMapProto.AWMap getItems() {
      return items_ == null ? feup.sdle.message.AWMapProto.AWMap.getDefaultInstance() : items_;
    }
    /**
     * <code>.feup.sdle.message.AWMap items = 1;</code>
     */
    @java.lang.Override
    public feup.sdle.message.AWMapProto.AWMapOrBuilder getItemsOrBuilder() {
      return items_ == null ? feup.sdle.message.AWMapProto.AWMap.getDefaultInstance() : items_;
    }

    public static final int LOCALIDENTIFIER_FIELD_NUMBER = 2;
    private feup.sdle.message.NodeIdentifierMessage.NodeIdentifier localIdentifier_;
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     * @return Whether the localIdentifier field is set.
     */
    @java.lang.Override
    public boolean hasLocalIdentifier() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     * @return The localIdentifier.
     */
    @java.lang.Override
    public feup.sdle.message.NodeIdentifierMessage.NodeIdentifier getLocalIdentifier() {
      return localIdentifier_ == null ? feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance() : localIdentifier_;
    }
    /**
     * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
     */
    @java.lang.Override
    public feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder getLocalIdentifierOrBuilder() {
      return localIdentifier_ == null ? feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance() : localIdentifier_;
    }

    public static final int REMOVEDCOUNTERS_FIELD_NUMBER = 3;
    private static final class RemovedCountersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>newDefaultInstance(
                  feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_ShoppingList_RemovedCountersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  feup.sdle.message.DottedValueProto.DottedValue.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> removedCounters_;
    private com.google.protobuf.MapField<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
    internalGetRemovedCounters() {
      if (removedCounters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RemovedCountersDefaultEntryHolder.defaultEntry);
      }
      return removedCounters_;
    }
    public int getRemovedCountersCount() {
      return internalGetRemovedCounters().getMap().size();
    }
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    @java.lang.Override
    public boolean containsRemovedCounters(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetRemovedCounters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRemovedCountersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> getRemovedCounters() {
      return getRemovedCountersMap();
    }
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> getRemovedCountersMap() {
      return internalGetRemovedCounters().getMap();
    }
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
feup.sdle.message.DottedValueProto.DottedValue getRemovedCountersOrDefault(
        java.lang.String key,
        /* nullable */
feup.sdle.message.DottedValueProto.DottedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> map =
          internalGetRemovedCounters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
     */
    @java.lang.Override
    public feup.sdle.message.DottedValueProto.DottedValue getRemovedCountersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> map =
          internalGetRemovedCounters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getItems());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getLocalIdentifier());
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetRemovedCounters(),
          RemovedCountersDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getItems());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLocalIdentifier());
      }
      for (java.util.Map.Entry<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> entry
           : internalGetRemovedCounters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
        removedCounters__ = RemovedCountersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, removedCounters__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof feup.sdle.message.DocumentProto.ShoppingList)) {
        return super.equals(obj);
      }
      feup.sdle.message.DocumentProto.ShoppingList other = (feup.sdle.message.DocumentProto.ShoppingList) obj;

      if (hasItems() != other.hasItems()) return false;
      if (hasItems()) {
        if (!getItems()
            .equals(other.getItems())) return false;
      }
      if (hasLocalIdentifier() != other.hasLocalIdentifier()) return false;
      if (hasLocalIdentifier()) {
        if (!getLocalIdentifier()
            .equals(other.getLocalIdentifier())) return false;
      }
      if (!internalGetRemovedCounters().equals(
          other.internalGetRemovedCounters())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasItems()) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItems().hashCode();
      }
      if (hasLocalIdentifier()) {
        hash = (37 * hash) + LOCALIDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getLocalIdentifier().hashCode();
      }
      if (!internalGetRemovedCounters().getMap().isEmpty()) {
        hash = (37 * hash) + REMOVEDCOUNTERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetRemovedCounters().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static feup.sdle.message.DocumentProto.ShoppingList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static feup.sdle.message.DocumentProto.ShoppingList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentProto.ShoppingList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(feup.sdle.message.DocumentProto.ShoppingList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code feup.sdle.message.ShoppingList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:feup.sdle.message.ShoppingList)
        feup.sdle.message.DocumentProto.ShoppingListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_ShoppingList_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 3:
            return internalGetRemovedCounters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableRemovedCounters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_ShoppingList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                feup.sdle.message.DocumentProto.ShoppingList.class, feup.sdle.message.DocumentProto.ShoppingList.Builder.class);
      }

      // Construct using feup.sdle.message.DocumentProto.ShoppingList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
          getLocalIdentifierFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        items_ = null;
        if (itemsBuilder_ != null) {
          itemsBuilder_.dispose();
          itemsBuilder_ = null;
        }
        localIdentifier_ = null;
        if (localIdentifierBuilder_ != null) {
          localIdentifierBuilder_.dispose();
          localIdentifierBuilder_ = null;
        }
        internalGetMutableRemovedCounters().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return feup.sdle.message.DocumentProto.internal_static_feup_sdle_message_ShoppingList_descriptor;
      }

      @java.lang.Override
      public feup.sdle.message.DocumentProto.ShoppingList getDefaultInstanceForType() {
        return feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance();
      }

      @java.lang.Override
      public feup.sdle.message.DocumentProto.ShoppingList build() {
        feup.sdle.message.DocumentProto.ShoppingList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public feup.sdle.message.DocumentProto.ShoppingList buildPartial() {
        feup.sdle.message.DocumentProto.ShoppingList result = new feup.sdle.message.DocumentProto.ShoppingList(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(feup.sdle.message.DocumentProto.ShoppingList result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.items_ = itemsBuilder_ == null
              ? items_
              : itemsBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.localIdentifier_ = localIdentifierBuilder_ == null
              ? localIdentifier_
              : localIdentifierBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.removedCounters_ = internalGetRemovedCounters().build(RemovedCountersDefaultEntryHolder.defaultEntry);
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof feup.sdle.message.DocumentProto.ShoppingList) {
          return mergeFrom((feup.sdle.message.DocumentProto.ShoppingList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(feup.sdle.message.DocumentProto.ShoppingList other) {
        if (other == feup.sdle.message.DocumentProto.ShoppingList.getDefaultInstance()) return this;
        if (other.hasItems()) {
          mergeItems(other.getItems());
        }
        if (other.hasLocalIdentifier()) {
          mergeLocalIdentifier(other.getLocalIdentifier());
        }
        internalGetMutableRemovedCounters().mergeFrom(
            other.internalGetRemovedCounters());
        bitField0_ |= 0x00000004;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getItemsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getLocalIdentifierFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
                removedCounters__ = input.readMessage(
                    RemovedCountersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableRemovedCounters().ensureBuilderMap().put(
                    removedCounters__.getKey(), removedCounters__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private feup.sdle.message.AWMapProto.AWMap items_;
      private com.google.protobuf.SingleFieldBuilder<
          feup.sdle.message.AWMapProto.AWMap, feup.sdle.message.AWMapProto.AWMap.Builder, feup.sdle.message.AWMapProto.AWMapOrBuilder> itemsBuilder_;
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       * @return Whether the items field is set.
       */
      public boolean hasItems() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       * @return The items.
       */
      public feup.sdle.message.AWMapProto.AWMap getItems() {
        if (itemsBuilder_ == null) {
          return items_ == null ? feup.sdle.message.AWMapProto.AWMap.getDefaultInstance() : items_;
        } else {
          return itemsBuilder_.getMessage();
        }
      }
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       */
      public Builder setItems(feup.sdle.message.AWMapProto.AWMap value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          items_ = value;
        } else {
          itemsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       */
      public Builder setItems(
          feup.sdle.message.AWMapProto.AWMap.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          items_ = builderForValue.build();
        } else {
          itemsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       */
      public Builder mergeItems(feup.sdle.message.AWMapProto.AWMap value) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            items_ != null &&
            items_ != feup.sdle.message.AWMapProto.AWMap.getDefaultInstance()) {
            getItemsBuilder().mergeFrom(value);
          } else {
            items_ = value;
          }
        } else {
          itemsBuilder_.mergeFrom(value);
        }
        if (items_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       */
      public Builder clearItems() {
        bitField0_ = (bitField0_ & ~0x00000001);
        items_ = null;
        if (itemsBuilder_ != null) {
          itemsBuilder_.dispose();
          itemsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       */
      public feup.sdle.message.AWMapProto.AWMap.Builder getItemsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getItemsFieldBuilder().getBuilder();
      }
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       */
      public feup.sdle.message.AWMapProto.AWMapOrBuilder getItemsOrBuilder() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilder();
        } else {
          return items_ == null ?
              feup.sdle.message.AWMapProto.AWMap.getDefaultInstance() : items_;
        }
      }
      /**
       * <code>.feup.sdle.message.AWMap items = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          feup.sdle.message.AWMapProto.AWMap, feup.sdle.message.AWMapProto.AWMap.Builder, feup.sdle.message.AWMapProto.AWMapOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              feup.sdle.message.AWMapProto.AWMap, feup.sdle.message.AWMapProto.AWMap.Builder, feup.sdle.message.AWMapProto.AWMapOrBuilder>(
                  getItems(),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private feup.sdle.message.NodeIdentifierMessage.NodeIdentifier localIdentifier_;
      private com.google.protobuf.SingleFieldBuilder<
          feup.sdle.message.NodeIdentifierMessage.NodeIdentifier, feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder, feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder> localIdentifierBuilder_;
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       * @return Whether the localIdentifier field is set.
       */
      public boolean hasLocalIdentifier() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       * @return The localIdentifier.
       */
      public feup.sdle.message.NodeIdentifierMessage.NodeIdentifier getLocalIdentifier() {
        if (localIdentifierBuilder_ == null) {
          return localIdentifier_ == null ? feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance() : localIdentifier_;
        } else {
          return localIdentifierBuilder_.getMessage();
        }
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public Builder setLocalIdentifier(feup.sdle.message.NodeIdentifierMessage.NodeIdentifier value) {
        if (localIdentifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          localIdentifier_ = value;
        } else {
          localIdentifierBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public Builder setLocalIdentifier(
          feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder builderForValue) {
        if (localIdentifierBuilder_ == null) {
          localIdentifier_ = builderForValue.build();
        } else {
          localIdentifierBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public Builder mergeLocalIdentifier(feup.sdle.message.NodeIdentifierMessage.NodeIdentifier value) {
        if (localIdentifierBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            localIdentifier_ != null &&
            localIdentifier_ != feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance()) {
            getLocalIdentifierBuilder().mergeFrom(value);
          } else {
            localIdentifier_ = value;
          }
        } else {
          localIdentifierBuilder_.mergeFrom(value);
        }
        if (localIdentifier_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public Builder clearLocalIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localIdentifier_ = null;
        if (localIdentifierBuilder_ != null) {
          localIdentifierBuilder_.dispose();
          localIdentifierBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder getLocalIdentifierBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLocalIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      public feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder getLocalIdentifierOrBuilder() {
        if (localIdentifierBuilder_ != null) {
          return localIdentifierBuilder_.getMessageOrBuilder();
        } else {
          return localIdentifier_ == null ?
              feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.getDefaultInstance() : localIdentifier_;
        }
      }
      /**
       * <code>.feup.sdle.message.NodeIdentifier localIdentifier = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          feup.sdle.message.NodeIdentifierMessage.NodeIdentifier, feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder, feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder> 
          getLocalIdentifierFieldBuilder() {
        if (localIdentifierBuilder_ == null) {
          localIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              feup.sdle.message.NodeIdentifierMessage.NodeIdentifier, feup.sdle.message.NodeIdentifierMessage.NodeIdentifier.Builder, feup.sdle.message.NodeIdentifierMessage.NodeIdentifierOrBuilder>(
                  getLocalIdentifier(),
                  getParentForChildren(),
                  isClean());
          localIdentifier_ = null;
        }
        return localIdentifierBuilder_;
      }

      private static final class RemovedCountersConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, feup.sdle.message.DottedValueProto.DottedValueOrBuilder, feup.sdle.message.DottedValueProto.DottedValue> {
        @java.lang.Override
        public feup.sdle.message.DottedValueProto.DottedValue build(feup.sdle.message.DottedValueProto.DottedValueOrBuilder val) {
          if (val instanceof feup.sdle.message.DottedValueProto.DottedValue) { return (feup.sdle.message.DottedValueProto.DottedValue) val; }
          return ((feup.sdle.message.DottedValueProto.DottedValue.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> defaultEntry() {
          return RemovedCountersDefaultEntryHolder.defaultEntry;
        }
      };
      private static final RemovedCountersConverter removedCountersConverter = new RemovedCountersConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, feup.sdle.message.DottedValueProto.DottedValueOrBuilder, feup.sdle.message.DottedValueProto.DottedValue, feup.sdle.message.DottedValueProto.DottedValue.Builder> removedCounters_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, feup.sdle.message.DottedValueProto.DottedValueOrBuilder, feup.sdle.message.DottedValueProto.DottedValue, feup.sdle.message.DottedValueProto.DottedValue.Builder>
          internalGetRemovedCounters() {
        if (removedCounters_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(removedCountersConverter);
        }
        return removedCounters_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, feup.sdle.message.DottedValueProto.DottedValueOrBuilder, feup.sdle.message.DottedValueProto.DottedValue, feup.sdle.message.DottedValueProto.DottedValue.Builder>
          internalGetMutableRemovedCounters() {
        if (removedCounters_ == null) {
          removedCounters_ = new com.google.protobuf.MapFieldBuilder<>(removedCountersConverter);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return removedCounters_;
      }
      public int getRemovedCountersCount() {
        return internalGetRemovedCounters().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
       */
      @java.lang.Override
      public boolean containsRemovedCounters(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetRemovedCounters().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getRemovedCountersMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> getRemovedCounters() {
        return getRemovedCountersMap();
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> getRemovedCountersMap() {
        return internalGetRemovedCounters().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
       */
      @java.lang.Override
      public /* nullable */
feup.sdle.message.DottedValueProto.DottedValue getRemovedCountersOrDefault(
          java.lang.String key,
          /* nullable */
feup.sdle.message.DottedValueProto.DottedValue defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValueOrBuilder> map = internalGetMutableRemovedCounters().ensureBuilderMap();
        return map.containsKey(key) ? removedCountersConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
       */
      @java.lang.Override
      public feup.sdle.message.DottedValueProto.DottedValue getRemovedCountersOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValueOrBuilder> map = internalGetMutableRemovedCounters().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return removedCountersConverter.build(map.get(key));
      }
      public Builder clearRemovedCounters() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableRemovedCounters().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
       */
      public Builder removeRemovedCounters(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableRemovedCounters().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue>
          getMutableRemovedCounters() {
        bitField0_ |= 0x00000004;
        return internalGetMutableRemovedCounters().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
       */
      public Builder putRemovedCounters(
          java.lang.String key,
          feup.sdle.message.DottedValueProto.DottedValue value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableRemovedCounters().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
       */
      public Builder putAllRemovedCounters(
          java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> values) {
        for (java.util.Map.Entry<java.lang.String, feup.sdle.message.DottedValueProto.DottedValue> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableRemovedCounters().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, .feup.sdle.message.DottedValue&gt; removedCounters = 3;</code>
       */
      public feup.sdle.message.DottedValueProto.DottedValue.Builder putRemovedCountersBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, feup.sdle.message.DottedValueProto.DottedValueOrBuilder> builderMap = internalGetMutableRemovedCounters().ensureBuilderMap();
        feup.sdle.message.DottedValueProto.DottedValueOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = feup.sdle.message.DottedValueProto.DottedValue.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof feup.sdle.message.DottedValueProto.DottedValue) {
          entry = ((feup.sdle.message.DottedValueProto.DottedValue) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (feup.sdle.message.DottedValueProto.DottedValue.Builder) entry;
      }

      // @@protoc_insertion_point(builder_scope:feup.sdle.message.ShoppingList)
    }

    // @@protoc_insertion_point(class_scope:feup.sdle.message.ShoppingList)
    private static final feup.sdle.message.DocumentProto.ShoppingList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new feup.sdle.message.DocumentProto.ShoppingList();
    }

    public static feup.sdle.message.DocumentProto.ShoppingList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShoppingList>
        PARSER = new com.google.protobuf.AbstractParser<ShoppingList>() {
      @java.lang.Override
      public ShoppingList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ShoppingList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShoppingList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public feup.sdle.message.DocumentProto.ShoppingList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feup_sdle_message_Document_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_feup_sdle_message_Document_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feup_sdle_message_ShoppingList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_feup_sdle_message_ShoppingList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feup_sdle_message_ShoppingList_RemovedCountersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_feup_sdle_message_ShoppingList_RemovedCountersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016document.proto\022\021feup.sdle.message\032\013awm" +
      "ap.proto\032\024nodeidentifier.proto\032\021dottedva" +
      "lue.proto\"{\n\010Document\0228\n\rshopping_list\030\001" +
      " \001(\0132\037.feup.sdle.message.ShoppingListH\000\022" +
      "\026\n\treplicate\030\002 \001(\010H\001\210\001\001B\017\n\rdocument_type" +
      "B\014\n\n_replicate\"\232\002\n\014ShoppingList\022\'\n\005items" +
      "\030\001 \001(\0132\030.feup.sdle.message.AWMap\022:\n\017loca" +
      "lIdentifier\030\002 \001(\0132!.feup.sdle.message.No" +
      "deIdentifier\022M\n\017removedCounters\030\003 \003(\01324." +
      "feup.sdle.message.ShoppingList.RemovedCo" +
      "untersEntry\032V\n\024RemovedCountersEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022-\n\005value\030\002 \001(\0132\036.feup.sdle.mess" +
      "age.DottedValue:\0028\001B\"\n\021feup.sdle.message" +
      "B\rDocumentProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          feup.sdle.message.AWMapProto.getDescriptor(),
          feup.sdle.message.NodeIdentifierMessage.getDescriptor(),
          feup.sdle.message.DottedValueProto.getDescriptor(),
        });
    internal_static_feup_sdle_message_Document_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_feup_sdle_message_Document_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_feup_sdle_message_Document_descriptor,
        new java.lang.String[] { "ShoppingList", "Replicate", "DocumentType", });
    internal_static_feup_sdle_message_ShoppingList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_feup_sdle_message_ShoppingList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_feup_sdle_message_ShoppingList_descriptor,
        new java.lang.String[] { "Items", "LocalIdentifier", "RemovedCounters", });
    internal_static_feup_sdle_message_ShoppingList_RemovedCountersEntry_descriptor =
      internal_static_feup_sdle_message_ShoppingList_descriptor.getNestedTypes().get(0);
    internal_static_feup_sdle_message_ShoppingList_RemovedCountersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_feup_sdle_message_ShoppingList_RemovedCountersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    feup.sdle.message.AWMapProto.getDescriptor();
    feup.sdle.message.NodeIdentifierMessage.getDescriptor();
    feup.sdle.message.DottedValueProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
