// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: documentrequest.proto

package feup.sdle.message;

public final class DocumentRequestProto {
  private DocumentRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DocumentRangeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DocumentRangeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.HashRange range = 1;</code>
     * @return Whether the range field is set.
     */
    boolean hasRange();
    /**
     * <code>.HashRange range = 1;</code>
     * @return The range.
     */
    feup.sdle.message.DocumentRequestProto.HashRange getRange();
    /**
     * <code>.HashRange range = 1;</code>
     */
    feup.sdle.message.DocumentRequestProto.HashRangeOrBuilder getRangeOrBuilder();
  }
  /**
   * Protobuf type {@code DocumentRangeRequest}
   */
  public static final class DocumentRangeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DocumentRangeRequest)
      DocumentRangeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DocumentRangeRequest.newBuilder() to construct.
    private DocumentRangeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DocumentRangeRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DocumentRangeRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return feup.sdle.message.DocumentRequestProto.internal_static_DocumentRangeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return feup.sdle.message.DocumentRequestProto.internal_static_DocumentRangeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              feup.sdle.message.DocumentRequestProto.DocumentRangeRequest.class, feup.sdle.message.DocumentRequestProto.DocumentRangeRequest.Builder.class);
    }

    public static final int RANGE_FIELD_NUMBER = 1;
    private feup.sdle.message.DocumentRequestProto.HashRange range_;
    /**
     * <code>.HashRange range = 1;</code>
     * @return Whether the range field is set.
     */
    @java.lang.Override
    public boolean hasRange() {
      return range_ != null;
    }
    /**
     * <code>.HashRange range = 1;</code>
     * @return The range.
     */
    @java.lang.Override
    public feup.sdle.message.DocumentRequestProto.HashRange getRange() {
      return range_ == null ? feup.sdle.message.DocumentRequestProto.HashRange.getDefaultInstance() : range_;
    }
    /**
     * <code>.HashRange range = 1;</code>
     */
    @java.lang.Override
    public feup.sdle.message.DocumentRequestProto.HashRangeOrBuilder getRangeOrBuilder() {
      return getRange();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (range_ != null) {
        output.writeMessage(1, getRange());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (range_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRange());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof feup.sdle.message.DocumentRequestProto.DocumentRangeRequest)) {
        return super.equals(obj);
      }
      feup.sdle.message.DocumentRequestProto.DocumentRangeRequest other = (feup.sdle.message.DocumentRequestProto.DocumentRangeRequest) obj;

      if (hasRange() != other.hasRange()) return false;
      if (hasRange()) {
        if (!getRange()
            .equals(other.getRange())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRange()) {
        hash = (37 * hash) + RANGE_FIELD_NUMBER;
        hash = (53 * hash) + getRange().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(feup.sdle.message.DocumentRequestProto.DocumentRangeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DocumentRangeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DocumentRangeRequest)
        feup.sdle.message.DocumentRequestProto.DocumentRangeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return feup.sdle.message.DocumentRequestProto.internal_static_DocumentRangeRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return feup.sdle.message.DocumentRequestProto.internal_static_DocumentRangeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                feup.sdle.message.DocumentRequestProto.DocumentRangeRequest.class, feup.sdle.message.DocumentRequestProto.DocumentRangeRequest.Builder.class);
      }

      // Construct using feup.sdle.message.DocumentRequestProto.DocumentRangeRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (rangeBuilder_ == null) {
          range_ = null;
        } else {
          range_ = null;
          rangeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return feup.sdle.message.DocumentRequestProto.internal_static_DocumentRangeRequest_descriptor;
      }

      @java.lang.Override
      public feup.sdle.message.DocumentRequestProto.DocumentRangeRequest getDefaultInstanceForType() {
        return feup.sdle.message.DocumentRequestProto.DocumentRangeRequest.getDefaultInstance();
      }

      @java.lang.Override
      public feup.sdle.message.DocumentRequestProto.DocumentRangeRequest build() {
        feup.sdle.message.DocumentRequestProto.DocumentRangeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public feup.sdle.message.DocumentRequestProto.DocumentRangeRequest buildPartial() {
        feup.sdle.message.DocumentRequestProto.DocumentRangeRequest result = new feup.sdle.message.DocumentRequestProto.DocumentRangeRequest(this);
        if (rangeBuilder_ == null) {
          result.range_ = range_;
        } else {
          result.range_ = rangeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof feup.sdle.message.DocumentRequestProto.DocumentRangeRequest) {
          return mergeFrom((feup.sdle.message.DocumentRequestProto.DocumentRangeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(feup.sdle.message.DocumentRequestProto.DocumentRangeRequest other) {
        if (other == feup.sdle.message.DocumentRequestProto.DocumentRangeRequest.getDefaultInstance()) return this;
        if (other.hasRange()) {
          mergeRange(other.getRange());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getRangeFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private feup.sdle.message.DocumentRequestProto.HashRange range_;
      private com.google.protobuf.SingleFieldBuilderV3<
          feup.sdle.message.DocumentRequestProto.HashRange, feup.sdle.message.DocumentRequestProto.HashRange.Builder, feup.sdle.message.DocumentRequestProto.HashRangeOrBuilder> rangeBuilder_;
      /**
       * <code>.HashRange range = 1;</code>
       * @return Whether the range field is set.
       */
      public boolean hasRange() {
        return rangeBuilder_ != null || range_ != null;
      }
      /**
       * <code>.HashRange range = 1;</code>
       * @return The range.
       */
      public feup.sdle.message.DocumentRequestProto.HashRange getRange() {
        if (rangeBuilder_ == null) {
          return range_ == null ? feup.sdle.message.DocumentRequestProto.HashRange.getDefaultInstance() : range_;
        } else {
          return rangeBuilder_.getMessage();
        }
      }
      /**
       * <code>.HashRange range = 1;</code>
       */
      public Builder setRange(feup.sdle.message.DocumentRequestProto.HashRange value) {
        if (rangeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          range_ = value;
          onChanged();
        } else {
          rangeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.HashRange range = 1;</code>
       */
      public Builder setRange(
          feup.sdle.message.DocumentRequestProto.HashRange.Builder builderForValue) {
        if (rangeBuilder_ == null) {
          range_ = builderForValue.build();
          onChanged();
        } else {
          rangeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.HashRange range = 1;</code>
       */
      public Builder mergeRange(feup.sdle.message.DocumentRequestProto.HashRange value) {
        if (rangeBuilder_ == null) {
          if (range_ != null) {
            range_ =
              feup.sdle.message.DocumentRequestProto.HashRange.newBuilder(range_).mergeFrom(value).buildPartial();
          } else {
            range_ = value;
          }
          onChanged();
        } else {
          rangeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.HashRange range = 1;</code>
       */
      public Builder clearRange() {
        if (rangeBuilder_ == null) {
          range_ = null;
          onChanged();
        } else {
          range_ = null;
          rangeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.HashRange range = 1;</code>
       */
      public feup.sdle.message.DocumentRequestProto.HashRange.Builder getRangeBuilder() {
        
        onChanged();
        return getRangeFieldBuilder().getBuilder();
      }
      /**
       * <code>.HashRange range = 1;</code>
       */
      public feup.sdle.message.DocumentRequestProto.HashRangeOrBuilder getRangeOrBuilder() {
        if (rangeBuilder_ != null) {
          return rangeBuilder_.getMessageOrBuilder();
        } else {
          return range_ == null ?
              feup.sdle.message.DocumentRequestProto.HashRange.getDefaultInstance() : range_;
        }
      }
      /**
       * <code>.HashRange range = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          feup.sdle.message.DocumentRequestProto.HashRange, feup.sdle.message.DocumentRequestProto.HashRange.Builder, feup.sdle.message.DocumentRequestProto.HashRangeOrBuilder> 
          getRangeFieldBuilder() {
        if (rangeBuilder_ == null) {
          rangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              feup.sdle.message.DocumentRequestProto.HashRange, feup.sdle.message.DocumentRequestProto.HashRange.Builder, feup.sdle.message.DocumentRequestProto.HashRangeOrBuilder>(
                  getRange(),
                  getParentForChildren(),
                  isClean());
          range_ = null;
        }
        return rangeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DocumentRangeRequest)
    }

    // @@protoc_insertion_point(class_scope:DocumentRangeRequest)
    private static final feup.sdle.message.DocumentRequestProto.DocumentRangeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new feup.sdle.message.DocumentRequestProto.DocumentRangeRequest();
    }

    public static feup.sdle.message.DocumentRequestProto.DocumentRangeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DocumentRangeRequest>
        PARSER = new com.google.protobuf.AbstractParser<DocumentRangeRequest>() {
      @java.lang.Override
      public DocumentRangeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DocumentRangeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DocumentRangeRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public feup.sdle.message.DocumentRequestProto.DocumentRangeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HashRangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HashRange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes start = 1;</code>
     * @return The start.
     */
    com.google.protobuf.ByteString getStart();

    /**
     * <code>bytes end = 2;</code>
     * @return The end.
     */
    com.google.protobuf.ByteString getEnd();
  }
  /**
   * Protobuf type {@code HashRange}
   */
  public static final class HashRange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HashRange)
      HashRangeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HashRange.newBuilder() to construct.
    private HashRange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HashRange() {
      start_ = com.google.protobuf.ByteString.EMPTY;
      end_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HashRange();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return feup.sdle.message.DocumentRequestProto.internal_static_HashRange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return feup.sdle.message.DocumentRequestProto.internal_static_HashRange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              feup.sdle.message.DocumentRequestProto.HashRange.class, feup.sdle.message.DocumentRequestProto.HashRange.Builder.class);
    }

    public static final int START_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString start_;
    /**
     * <code>bytes start = 1;</code>
     * @return The start.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStart() {
      return start_;
    }

    public static final int END_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString end_;
    /**
     * <code>bytes end = 2;</code>
     * @return The end.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEnd() {
      return end_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!start_.isEmpty()) {
        output.writeBytes(1, start_);
      }
      if (!end_.isEmpty()) {
        output.writeBytes(2, end_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!start_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, start_);
      }
      if (!end_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, end_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof feup.sdle.message.DocumentRequestProto.HashRange)) {
        return super.equals(obj);
      }
      feup.sdle.message.DocumentRequestProto.HashRange other = (feup.sdle.message.DocumentRequestProto.HashRange) obj;

      if (!getStart()
          .equals(other.getStart())) return false;
      if (!getEnd()
          .equals(other.getEnd())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart().hashCode();
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DocumentRequestProto.HashRange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(feup.sdle.message.DocumentRequestProto.HashRange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HashRange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HashRange)
        feup.sdle.message.DocumentRequestProto.HashRangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return feup.sdle.message.DocumentRequestProto.internal_static_HashRange_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return feup.sdle.message.DocumentRequestProto.internal_static_HashRange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                feup.sdle.message.DocumentRequestProto.HashRange.class, feup.sdle.message.DocumentRequestProto.HashRange.Builder.class);
      }

      // Construct using feup.sdle.message.DocumentRequestProto.HashRange.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        start_ = com.google.protobuf.ByteString.EMPTY;

        end_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return feup.sdle.message.DocumentRequestProto.internal_static_HashRange_descriptor;
      }

      @java.lang.Override
      public feup.sdle.message.DocumentRequestProto.HashRange getDefaultInstanceForType() {
        return feup.sdle.message.DocumentRequestProto.HashRange.getDefaultInstance();
      }

      @java.lang.Override
      public feup.sdle.message.DocumentRequestProto.HashRange build() {
        feup.sdle.message.DocumentRequestProto.HashRange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public feup.sdle.message.DocumentRequestProto.HashRange buildPartial() {
        feup.sdle.message.DocumentRequestProto.HashRange result = new feup.sdle.message.DocumentRequestProto.HashRange(this);
        result.start_ = start_;
        result.end_ = end_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof feup.sdle.message.DocumentRequestProto.HashRange) {
          return mergeFrom((feup.sdle.message.DocumentRequestProto.HashRange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(feup.sdle.message.DocumentRequestProto.HashRange other) {
        if (other == feup.sdle.message.DocumentRequestProto.HashRange.getDefaultInstance()) return this;
        if (other.getStart() != com.google.protobuf.ByteString.EMPTY) {
          setStart(other.getStart());
        }
        if (other.getEnd() != com.google.protobuf.ByteString.EMPTY) {
          setEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                start_ = input.readBytes();

                break;
              } // case 10
              case 18: {
                end_ = input.readBytes();

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private com.google.protobuf.ByteString start_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes start = 1;</code>
       * @return The start.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getStart() {
        return start_;
      }
      /**
       * <code>bytes start = 1;</code>
       * @param value The start to set.
       * @return This builder for chaining.
       */
      public Builder setStart(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes start = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStart() {
        
        start_ = getDefaultInstance().getStart();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString end_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes end = 2;</code>
       * @return The end.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEnd() {
        return end_;
      }
      /**
       * <code>bytes end = 2;</code>
       * @param value The end to set.
       * @return This builder for chaining.
       */
      public Builder setEnd(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes end = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnd() {
        
        end_ = getDefaultInstance().getEnd();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HashRange)
    }

    // @@protoc_insertion_point(class_scope:HashRange)
    private static final feup.sdle.message.DocumentRequestProto.HashRange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new feup.sdle.message.DocumentRequestProto.HashRange();
    }

    public static feup.sdle.message.DocumentRequestProto.HashRange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HashRange>
        PARSER = new com.google.protobuf.AbstractParser<HashRange>() {
      @java.lang.Override
      public HashRange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HashRange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HashRange> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public feup.sdle.message.DocumentRequestProto.HashRange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DocumentRangeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DocumentRangeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HashRange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HashRange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025documentrequest.proto\"1\n\024DocumentRange" +
      "Request\022\031\n\005range\030\001 \001(\0132\n.HashRange\"\'\n\tHa" +
      "shRange\022\r\n\005start\030\001 \001(\014\022\013\n\003end\030\002 \001(\014B)\n\021f" +
      "eup.sdle.messageB\024DocumentRequestProtob\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DocumentRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DocumentRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DocumentRangeRequest_descriptor,
        new java.lang.String[] { "Range", });
    internal_static_HashRange_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HashRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HashRange_descriptor,
        new java.lang.String[] { "Start", "End", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
