// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dottedvalue.proto
// Protobuf Java Version: 4.28.3

package feup.sdle.message;

public final class DottedValueProto {
  private DottedValueProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      DottedValueProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DottedValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:feup.sdle.message.DottedValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 identifier = 1;</code>
     * @return The identifier.
     */
    int getIdentifier();

    /**
     * <code>int32 event = 2;</code>
     * @return The event.
     */
    int getEvent();

    /**
     * <code>int32 value_int = 3;</code>
     * @return Whether the valueInt field is set.
     */
    boolean hasValueInt();
    /**
     * <code>int32 value_int = 3;</code>
     * @return The valueInt.
     */
    int getValueInt();

    /**
     * <code>string value_str = 4;</code>
     * @return Whether the valueStr field is set.
     */
    boolean hasValueStr();
    /**
     * <code>string value_str = 4;</code>
     * @return The valueStr.
     */
    java.lang.String getValueStr();
    /**
     * <code>string value_str = 4;</code>
     * @return The bytes for valueStr.
     */
    com.google.protobuf.ByteString
        getValueStrBytes();

    /**
     * <code>bytes value_obj = 5;</code>
     * @return Whether the valueObj field is set.
     */
    boolean hasValueObj();
    /**
     * <code>bytes value_obj = 5;</code>
     * @return The valueObj.
     */
    com.google.protobuf.ByteString getValueObj();

    feup.sdle.message.DottedValueProto.DottedValue.ValueTypeCase getValueTypeCase();
  }
  /**
   * Protobuf type {@code feup.sdle.message.DottedValue}
   */
  public static final class DottedValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:feup.sdle.message.DottedValue)
      DottedValueOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        DottedValue.class.getName());
    }
    // Use DottedValue.newBuilder() to construct.
    private DottedValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DottedValue() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return feup.sdle.message.DottedValueProto.internal_static_feup_sdle_message_DottedValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return feup.sdle.message.DottedValueProto.internal_static_feup_sdle_message_DottedValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              feup.sdle.message.DottedValueProto.DottedValue.class, feup.sdle.message.DottedValueProto.DottedValue.Builder.class);
    }

    private int valueTypeCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object valueType_;
    public enum ValueTypeCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      VALUE_INT(3),
      VALUE_STR(4),
      VALUE_OBJ(5),
      VALUETYPE_NOT_SET(0);
      private final int value;
      private ValueTypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueTypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueTypeCase forNumber(int value) {
        switch (value) {
          case 3: return VALUE_INT;
          case 4: return VALUE_STR;
          case 5: return VALUE_OBJ;
          case 0: return VALUETYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueTypeCase
    getValueTypeCase() {
      return ValueTypeCase.forNumber(
          valueTypeCase_);
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    private int identifier_ = 0;
    /**
     * <code>int32 identifier = 1;</code>
     * @return The identifier.
     */
    @java.lang.Override
    public int getIdentifier() {
      return identifier_;
    }

    public static final int EVENT_FIELD_NUMBER = 2;
    private int event_ = 0;
    /**
     * <code>int32 event = 2;</code>
     * @return The event.
     */
    @java.lang.Override
    public int getEvent() {
      return event_;
    }

    public static final int VALUE_INT_FIELD_NUMBER = 3;
    /**
     * <code>int32 value_int = 3;</code>
     * @return Whether the valueInt field is set.
     */
    @java.lang.Override
    public boolean hasValueInt() {
      return valueTypeCase_ == 3;
    }
    /**
     * <code>int32 value_int = 3;</code>
     * @return The valueInt.
     */
    @java.lang.Override
    public int getValueInt() {
      if (valueTypeCase_ == 3) {
        return (java.lang.Integer) valueType_;
      }
      return 0;
    }

    public static final int VALUE_STR_FIELD_NUMBER = 4;
    /**
     * <code>string value_str = 4;</code>
     * @return Whether the valueStr field is set.
     */
    public boolean hasValueStr() {
      return valueTypeCase_ == 4;
    }
    /**
     * <code>string value_str = 4;</code>
     * @return The valueStr.
     */
    public java.lang.String getValueStr() {
      java.lang.Object ref = "";
      if (valueTypeCase_ == 4) {
        ref = valueType_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueTypeCase_ == 4) {
          valueType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string value_str = 4;</code>
     * @return The bytes for valueStr.
     */
    public com.google.protobuf.ByteString
        getValueStrBytes() {
      java.lang.Object ref = "";
      if (valueTypeCase_ == 4) {
        ref = valueType_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueTypeCase_ == 4) {
          valueType_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_OBJ_FIELD_NUMBER = 5;
    /**
     * <code>bytes value_obj = 5;</code>
     * @return Whether the valueObj field is set.
     */
    @java.lang.Override
    public boolean hasValueObj() {
      return valueTypeCase_ == 5;
    }
    /**
     * <code>bytes value_obj = 5;</code>
     * @return The valueObj.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValueObj() {
      if (valueTypeCase_ == 5) {
        return (com.google.protobuf.ByteString) valueType_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (identifier_ != 0) {
        output.writeInt32(1, identifier_);
      }
      if (event_ != 0) {
        output.writeInt32(2, event_);
      }
      if (valueTypeCase_ == 3) {
        output.writeInt32(
            3, (int)((java.lang.Integer) valueType_));
      }
      if (valueTypeCase_ == 4) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, valueType_);
      }
      if (valueTypeCase_ == 5) {
        output.writeBytes(
            5, (com.google.protobuf.ByteString) valueType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (identifier_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, identifier_);
      }
      if (event_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, event_);
      }
      if (valueTypeCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              3, (int)((java.lang.Integer) valueType_));
      }
      if (valueTypeCase_ == 4) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, valueType_);
      }
      if (valueTypeCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              5, (com.google.protobuf.ByteString) valueType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof feup.sdle.message.DottedValueProto.DottedValue)) {
        return super.equals(obj);
      }
      feup.sdle.message.DottedValueProto.DottedValue other = (feup.sdle.message.DottedValueProto.DottedValue) obj;

      if (getIdentifier()
          != other.getIdentifier()) return false;
      if (getEvent()
          != other.getEvent()) return false;
      if (!getValueTypeCase().equals(other.getValueTypeCase())) return false;
      switch (valueTypeCase_) {
        case 3:
          if (getValueInt()
              != other.getValueInt()) return false;
          break;
        case 4:
          if (!getValueStr()
              .equals(other.getValueStr())) return false;
          break;
        case 5:
          if (!getValueObj()
              .equals(other.getValueObj())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + getEvent();
      switch (valueTypeCase_) {
        case 3:
          hash = (37 * hash) + VALUE_INT_FIELD_NUMBER;
          hash = (53 * hash) + getValueInt();
          break;
        case 4:
          hash = (37 * hash) + VALUE_STR_FIELD_NUMBER;
          hash = (53 * hash) + getValueStr().hashCode();
          break;
        case 5:
          hash = (37 * hash) + VALUE_OBJ_FIELD_NUMBER;
          hash = (53 * hash) + getValueObj().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static feup.sdle.message.DottedValueProto.DottedValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static feup.sdle.message.DottedValueProto.DottedValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static feup.sdle.message.DottedValueProto.DottedValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(feup.sdle.message.DottedValueProto.DottedValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code feup.sdle.message.DottedValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:feup.sdle.message.DottedValue)
        feup.sdle.message.DottedValueProto.DottedValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return feup.sdle.message.DottedValueProto.internal_static_feup_sdle_message_DottedValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return feup.sdle.message.DottedValueProto.internal_static_feup_sdle_message_DottedValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                feup.sdle.message.DottedValueProto.DottedValue.class, feup.sdle.message.DottedValueProto.DottedValue.Builder.class);
      }

      // Construct using feup.sdle.message.DottedValueProto.DottedValue.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        identifier_ = 0;
        event_ = 0;
        valueTypeCase_ = 0;
        valueType_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return feup.sdle.message.DottedValueProto.internal_static_feup_sdle_message_DottedValue_descriptor;
      }

      @java.lang.Override
      public feup.sdle.message.DottedValueProto.DottedValue getDefaultInstanceForType() {
        return feup.sdle.message.DottedValueProto.DottedValue.getDefaultInstance();
      }

      @java.lang.Override
      public feup.sdle.message.DottedValueProto.DottedValue build() {
        feup.sdle.message.DottedValueProto.DottedValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public feup.sdle.message.DottedValueProto.DottedValue buildPartial() {
        feup.sdle.message.DottedValueProto.DottedValue result = new feup.sdle.message.DottedValueProto.DottedValue(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(feup.sdle.message.DottedValueProto.DottedValue result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.identifier_ = identifier_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.event_ = event_;
        }
      }

      private void buildPartialOneofs(feup.sdle.message.DottedValueProto.DottedValue result) {
        result.valueTypeCase_ = valueTypeCase_;
        result.valueType_ = this.valueType_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof feup.sdle.message.DottedValueProto.DottedValue) {
          return mergeFrom((feup.sdle.message.DottedValueProto.DottedValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(feup.sdle.message.DottedValueProto.DottedValue other) {
        if (other == feup.sdle.message.DottedValueProto.DottedValue.getDefaultInstance()) return this;
        if (other.getIdentifier() != 0) {
          setIdentifier(other.getIdentifier());
        }
        if (other.getEvent() != 0) {
          setEvent(other.getEvent());
        }
        switch (other.getValueTypeCase()) {
          case VALUE_INT: {
            setValueInt(other.getValueInt());
            break;
          }
          case VALUE_STR: {
            valueTypeCase_ = 4;
            valueType_ = other.valueType_;
            onChanged();
            break;
          }
          case VALUE_OBJ: {
            setValueObj(other.getValueObj());
            break;
          }
          case VALUETYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                identifier_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                event_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                valueType_ = input.readInt32();
                valueTypeCase_ = 3;
                break;
              } // case 24
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                valueTypeCase_ = 4;
                valueType_ = s;
                break;
              } // case 34
              case 42: {
                valueType_ = input.readBytes();
                valueTypeCase_ = 5;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int valueTypeCase_ = 0;
      private java.lang.Object valueType_;
      public ValueTypeCase
          getValueTypeCase() {
        return ValueTypeCase.forNumber(
            valueTypeCase_);
      }

      public Builder clearValueType() {
        valueTypeCase_ = 0;
        valueType_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int identifier_ ;
      /**
       * <code>int32 identifier = 1;</code>
       * @return The identifier.
       */
      @java.lang.Override
      public int getIdentifier() {
        return identifier_;
      }
      /**
       * <code>int32 identifier = 1;</code>
       * @param value The identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifier(int value) {

        identifier_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 identifier = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000001);
        identifier_ = 0;
        onChanged();
        return this;
      }

      private int event_ ;
      /**
       * <code>int32 event = 2;</code>
       * @return The event.
       */
      @java.lang.Override
      public int getEvent() {
        return event_;
      }
      /**
       * <code>int32 event = 2;</code>
       * @param value The event to set.
       * @return This builder for chaining.
       */
      public Builder setEvent(int value) {

        event_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 event = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        event_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>int32 value_int = 3;</code>
       * @return Whether the valueInt field is set.
       */
      public boolean hasValueInt() {
        return valueTypeCase_ == 3;
      }
      /**
       * <code>int32 value_int = 3;</code>
       * @return The valueInt.
       */
      public int getValueInt() {
        if (valueTypeCase_ == 3) {
          return (java.lang.Integer) valueType_;
        }
        return 0;
      }
      /**
       * <code>int32 value_int = 3;</code>
       * @param value The valueInt to set.
       * @return This builder for chaining.
       */
      public Builder setValueInt(int value) {

        valueTypeCase_ = 3;
        valueType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 value_int = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueInt() {
        if (valueTypeCase_ == 3) {
          valueTypeCase_ = 0;
          valueType_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string value_str = 4;</code>
       * @return Whether the valueStr field is set.
       */
      @java.lang.Override
      public boolean hasValueStr() {
        return valueTypeCase_ == 4;
      }
      /**
       * <code>string value_str = 4;</code>
       * @return The valueStr.
       */
      @java.lang.Override
      public java.lang.String getValueStr() {
        java.lang.Object ref = "";
        if (valueTypeCase_ == 4) {
          ref = valueType_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueTypeCase_ == 4) {
            valueType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value_str = 4;</code>
       * @return The bytes for valueStr.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueStrBytes() {
        java.lang.Object ref = "";
        if (valueTypeCase_ == 4) {
          ref = valueType_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueTypeCase_ == 4) {
            valueType_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value_str = 4;</code>
       * @param value The valueStr to set.
       * @return This builder for chaining.
       */
      public Builder setValueStr(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        valueTypeCase_ = 4;
        valueType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value_str = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueStr() {
        if (valueTypeCase_ == 4) {
          valueTypeCase_ = 0;
          valueType_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string value_str = 4;</code>
       * @param value The bytes for valueStr to set.
       * @return This builder for chaining.
       */
      public Builder setValueStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        valueTypeCase_ = 4;
        valueType_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes value_obj = 5;</code>
       * @return Whether the valueObj field is set.
       */
      public boolean hasValueObj() {
        return valueTypeCase_ == 5;
      }
      /**
       * <code>bytes value_obj = 5;</code>
       * @return The valueObj.
       */
      public com.google.protobuf.ByteString getValueObj() {
        if (valueTypeCase_ == 5) {
          return (com.google.protobuf.ByteString) valueType_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>bytes value_obj = 5;</code>
       * @param value The valueObj to set.
       * @return This builder for chaining.
       */
      public Builder setValueObj(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        valueTypeCase_ = 5;
        valueType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value_obj = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueObj() {
        if (valueTypeCase_ == 5) {
          valueTypeCase_ = 0;
          valueType_ = null;
          onChanged();
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:feup.sdle.message.DottedValue)
    }

    // @@protoc_insertion_point(class_scope:feup.sdle.message.DottedValue)
    private static final feup.sdle.message.DottedValueProto.DottedValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new feup.sdle.message.DottedValueProto.DottedValue();
    }

    public static feup.sdle.message.DottedValueProto.DottedValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DottedValue>
        PARSER = new com.google.protobuf.AbstractParser<DottedValue>() {
      @java.lang.Override
      public DottedValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DottedValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DottedValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public feup.sdle.message.DottedValueProto.DottedValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feup_sdle_message_DottedValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_feup_sdle_message_DottedValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021dottedvalue.proto\022\021feup.sdle.message\"}" +
      "\n\013DottedValue\022\022\n\nidentifier\030\001 \001(\005\022\r\n\005eve" +
      "nt\030\002 \001(\005\022\023\n\tvalue_int\030\003 \001(\005H\000\022\023\n\tvalue_s" +
      "tr\030\004 \001(\tH\000\022\023\n\tvalue_obj\030\005 \001(\014H\000B\014\n\nvalue" +
      "_typeB%\n\021feup.sdle.messageB\020DottedValueP" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_feup_sdle_message_DottedValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_feup_sdle_message_DottedValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_feup_sdle_message_DottedValue_descriptor,
        new java.lang.String[] { "Identifier", "Event", "ValueInt", "ValueStr", "ValueObj", "ValueType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
